Up to speed with experimental

diff --git a/deploy/pipelines/templates/collect-log-files.yaml b/deploy/pipelines/templates/collect-log-files.yaml
--- a/deploy/pipelines/templates/collect-log-files.yaml
+++ b/deploy/pipelines/templates/collect-log-files.yaml
@@ -3,9 +3,9 @@ parameters:
 steps:
   - script: |
       #!/bin/bash
-
-      # Ensure that the script fails if a command fails. 
-      set -e
+      # Exit immediately if a command exits with a non-zero status.
+      # Treat unset variables as an error when substituting.
+      set -eu
 
       if [ -d ${LOG_PATH} ] && [ $(ls ${LOG_PATH}/*.zip | wc -l ) -gt 0 ]; then
         echo "Found log files in ${LOG_PATH}"
@@ -45,6 +45,9 @@ steps:
 
   - script: |
       #!/bin/bash
+      # Exit immediately if a command exits with a non-zero status.
+      # Treat unset variables as an error when substituting.
+      set -eu
 
       timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S%:z")
 
diff --git a/deploy/pipelines/templates/run-ansible.yaml b/deploy/pipelines/templates/run-ansible.yaml
--- a/deploy/pipelines/templates/run-ansible.yaml
+++ b/deploy/pipelines/templates/run-ansible.yaml
@@ -13,11 +13,17 @@ parameters:
     sapParams: ''
 steps:
 - script: |
+    #!/bin/bash
+    # Exit immediately if a command exits with a non-zero status.
+    # Treat unset variables as an error when substituting.
+    set -eu
+
     #Stage could be executed on a different machine by default, need to login again for ansible
     #If the deployer_file exists we run on a deployer configured by the framework instead of a azdo hosted one
 
     deployer_file=/etc/profile.d/deploy_server.sh
     if [ -f "$deployer_file" ]; then
+      echo "##[section]Running on a deployer..."
       az login --identity --allow-no-subscriptions --output none
       noAccess=$( az account show --query name | grep  "N/A(tenant level account)")
 
@@ -25,34 +31,23 @@ steps:
         az account set --subscription $AZURE_SUBSCRIPTION_ID --output none
       fi
     else
+      echo "##[section]Running on an Azure DevOps agent..."
       az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID --output none
       az account set --subscription $AZURE_SUBSCRIPTION_ID --output none
 
     fi
 
     if [ ! -f $PARAMETERS_FOLDER/sshkey ]; then
+      echo "##[section]Retrieving sshkey..."
       az keyvault secret show --name $SSH_KEY_NAME --vault-name $VAULT_NAME --query value -o tsv > $PARAMETERS_FOLDER/sshkey
       sudo chmod 600 $PARAMETERS_FOLDER/sshkey
     fi
 
-    ls $PARAMETERS_FOLDER
-
-    if [ $EXTRA_PARAMS == '$(ExtraParams)' ]; then
-      ansible-playbook -i $INVENTORY \
-                      --private-key $PARAMETERS_FOLDER/sshkey \
-                      -e $SAP_PARAMS \
-                      -e "_workspace_directory=$PARAMETERS_FOLDER" \
-                      $ANSIBLE_FILE_PATH
-
-    else
-      ansible-playbook -i $INVENTORY \
-                      --private-key $PARAMETERS_FOLDER/sshkey \
-                      -e $SAP_PARAMS \
-                      -e "_workspace_directory=$PARAMETERS_FOLDER" \
-                      $EXTRA_PARAMS \
-                      $ANSIBLE_FILE_PATH
-    fi
-
+    command="ansible-playbook -i $INVENTORY --private-key $PARAMETERS_FOLDER/sshkey -e $SAP_PARAMS -e "_workspace_directory=$PARAMETERS_FOLDER" $EXTRA_PARAMS $ANSIBLE_FILE_PATH"
+    echo "##[section]Executing [$command]..."
+    echo "##[group]- output"
+    eval $command
+    echo "##[endgroup]"
 
   displayName:                      ${{ parameters.displayName }}
   env:
