Bring the internal changes

diff --git a/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl b/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
--- a/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
+++ b/deploy/terraform/terraform-units/modules/sap_deployer/templates/configure_deployer.sh.tmpl
@@ -72,29 +72,10 @@ AGENTNAME=$(hostname)
 #
 # Ansible Version settings
 #
-ansible_version="$${ansible_version:-2.15}"
+ansible_version="$${ansible_version:-2.13}"
 ansible_major="$${ansible_version%%.*}"
 ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
 
-case "$(get_distro_name)" in
-(ubuntu|sles)
-  rel=$(lsb_release -a | grep Release | cut -d':' -f2 | xargs)
-  # Ubuntu 20.04 (Focal Fossa)
-  if [ "$rel" == "20.04" ]; then
-    ansible_version="$${ansible_version:-2.13}"
-    ansible_major="$${ansible_version%%.*}"
-    ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
-  fi
-  if [ "$rel" == "18.04" ]; then
-    ansible_version="$${ansible_version:-2.13}"
-    ansible_major="$${ansible_version%%.*}"
-    ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
-  fi
-  ;;
-esac
-ansible_version="$${ansible_version:-2.15}"
-ansible_major="$${ansible_version%%.*}"
-ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
 
 #
 # Utility Functions
@@ -184,7 +165,9 @@ pkg_mgr_refresh()
         sudo "$${pkg_mgr}" update --quiet
         ;;
       zypper)
+        set +o errexit
         sudo "$${pkg_mgr}" --gpg-auto-import-keys --quiet refresh
+        set -o errexit
         ;;
       yum)
         sudo "$${pkg_mgr}" update --quiet
@@ -212,7 +195,9 @@ pkg_mgr_upgrade()
         sudo "$${pkg_mgr}" upgrade --quiet -y
         ;;
       zypper)
+        set +o errexit
         sudo "$${pkg_mgr}" --gpg-auto-import-keys --non-interactive patch
+        set -o errexit
         ;;
       yum)
         sudo "$${pkg_mgr}" upgrade --quiet -y
@@ -309,7 +294,52 @@ else
         ;;
     esac
 
+    echo "Set ansible version for specific distros"
+    echo ""
+    case "$(get_distro_name)" in
+    (ubuntu)
+      echo "we are inside ubuntu"
+      rel=$(lsb_release -a | grep Release | cut -d':' -f2 | xargs)
+      if [ "$rel" == "22.04" ]; then
+        ansible_version="$${ansible_version:-2.15}"
+        ansible_major="$${ansible_version%%.*}"
+        ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
+      fi
+      ;;
+    (sles)
+      echo "we are inside sles"
+      if [ "$(get_distro_version)" == "15.3" ]; then
+        ansible_version="2.11"
+        ansible_major="$${ansible_version%%.*}"
+        ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
+        # Ansible installation directories
+        ansible_base="/opt/ansible"
+        ansible_bin="$${ansible_base}/bin"
+        ansible_venv="$${ansible_base}/venv/$${ansible_version}"
+        ansible_venv_bin="$${ansible_venv}/bin"
+        ansible_collections="$${ansible_base}/collections"
+        ansible_pip3="$${ansible_venv_bin}/pip3"
+        sudo python3 -m pip install virtualenv;
+      elif [ "$(get_distro_version)" == "15.5" ]; then
+        ansible_version="2.11"
+        ansible_major="$${ansible_version%%.*}"
+        ansible_minor=$(echo "$${ansible_version}." | cut -d . -f 2)
+        # Ansible installation directories
+        ansible_base="/opt/ansible"
+        ansible_bin="$${ansible_base}/bin"
+        ansible_venv="$${ansible_base}/venv/$${ansible_version}"
+        ansible_venv_bin="$${ansible_venv}/bin"
+        ansible_collections="$${ansible_base}/collections"
+        ansible_pip3="$${ansible_venv_bin}/pip3"
+        sudo python3 -m pip install virtualenv;
+      fi
+      ;;
+    (*)
+      echo "we are in the default case statement"
+      ;;
+    esac
 
+    echo "Ansible version: $${ansible_version}"
     # List of required packages whose names are common to all supported distros
     required_pkgs=(
         git
@@ -322,14 +352,16 @@ else
     )
 
     cli_pkgs=(
-        azure-cli
     )
 
 
     # Include distro version agnostic packages into required packages list
     case "$(get_distro_name)" in
     (ubuntu)
-        required_pkgs+=(
+       cli_pkgs+=(
+            azure-cli
+        )
+       required_pkgs+=(
             sshpass
             python3-pip
             python3-virtualenv
@@ -342,11 +374,13 @@ else
         required_pkgs+=(
             curl
             python3-pip
-            python3-virtualenv
             lsb-release
         )
         ;;
     (rhel)
+       cli_pkgs+=(
+            azure-cli
+        )
         required_pkgs+=(
             sshpass
             python36
@@ -365,7 +399,6 @@ else
 
     # Upgrade packages
     pkg_mgr_upgrade
-
 
     # Ensure our package metadata cache is up to date
     pkg_mgr_refresh
@@ -422,6 +455,11 @@ else
         sudo apt autoremove -y
         sudo apt update -y
       fi
+      if [ "$(get_distro_version)" == "15.3" ]; then
+        set +o errexit
+        sudo zypper rm -y --clean-deps azure-cli
+        set -o errexit
+      fi
       ;;
     esac
 
@@ -444,10 +482,15 @@ else
         sudo apt-get install azure-cli -y
         ;;
     (sles)
-        echo "Getting the Microsoft Key"
-        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
-        sudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
-        sudo zypper install --from azure-cli azure-cli
+        if [ -f /home/$${local_user}/repos_configured ]; then
+          sudo zypper install -y --from azure-cli azure-cli
+        else
+          sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
+          sudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
+          sudo touch /home/$${local_user}/repos_configured
+          sudo zypper install -y --from azure-cli azure-cli
+        fi
+
         ;;
     (rhel*)
         sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
@@ -458,23 +501,7 @@ else
 
     set +o errexit
     pkg_mgr_install "$${cli_pkgs[@]}"
-
     set -o errexit
-
-    # Install dotNet
-    case "$(get_distro_name)" in
-    (ubuntu)
-        sudo snap install dotnet-sdk --classic --channel=7.0
-        sudo snap alias dotnet-sdk.dotnet dotnet
-        ;;
-    (sles)
-        sudo snap install dotnet-sdk --classic --channel=7.0
-        sudo snap alias dotnet-sdk.dotnet dotnet
-        ;;
-     (rhel*)
-        sudo dnf install dotnet-sdk-7.0 -y
-        ;;
-    esac
 
     # Install Ansible
     case "$(get_distro_name)" in
@@ -582,7 +609,7 @@ else
         # ansible-lint
 
         # argcomplete
-        # activate-global-python-argcomplete
+        activate-global-python-argcomplete
 
         # yamllint
         # yamllint
@@ -601,30 +628,56 @@ else
 
     # Install Ansible collections under the ANSIBLE_COLLECTIONS_PATHS for all users.
     sudo mkdir -p "$${ansible_collections}"
+
+    set +o xtrace
+
     sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install ansible.windows --force --collections-path "$${ansible_collections}"
     sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install ansible.posix --force --collections-path "$${ansible_collections}"
     sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install ansible.utils --force --collections-path "$${ansible_collections}"
-    sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install ansible.netcommon:5.1.2 --force --collections-path "$${ansible_collections}"
     sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install community.windows --force --collections-path "$${ansible_collections}"
-    sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install community.general --force --collections-path "$${ansible_collections}"
+
+    if [[ "$${ansible_version}" == "2.11" ]]; then
+      # ansible galaxy upstream has changed. Some collections are only available for install via old-galaxy.ansible.com
+      # https://github.com/ansible/ansible/issues/81830
+      # https://stackoverflow.com/questions/77225047/gitlab-pipeline-to-install-ansible-galaxy-role-fails/77238083#77238083
+      echo "Installing some ansible collections from old-galaxy.ansible.com"
+      sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install community.general --force --collections-path "$${ansible_collections}" --server="https://old-galaxy.ansible.com" --ignore-certs
+      sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install ansible.netcommon --force --collections-path "$${ansible_collections}" --server="https://old-galaxy.ansible.com" --ignore-certs
+    else
+      echo "Installing community.general"
+      sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install community.general --force --collections-path "$${ansible_collections}"
+      echo "Installing ansible.netcommon:5.1.2"
+      sudo -H "$${ansible_venv_bin}/ansible-galaxy" collection install ansible.netcommon:5.1.2 --force --collections-path "$${ansible_collections}"
+    fi
+    set -o xtrace
+
     #
     # Create /etc/profile.d script to setup environment for interactive sessions
     #
     echo '# Configure environment settings for deployer interactive sessions' | sudo tee /etc/profile.d/deploy_server.sh
 
-    export PATH="$${PATH}":"$${ansible_bin}":"$${tf_bin}"
-
     # Set env for ansible
     echo export ANSIBLE_HOST_KEY_CHECKING=False | sudo tee -a /etc/profile.d/deploy_server.sh
     echo export ANSIBLE_COLLECTIONS_PATHS="$${ansible_collections}" | sudo tee -a /etc/profile.d/deploy_server.sh
 
+    export DOTNET_INSTALL_DIR=/opt/dotnet
+
+    sudo mkdir -p $${DOTNET_INSTALL_DIR}
+
     case "$(get_distro_name)" in
-    (ubuntu|sles)
+    (ubuntu)
         echo "export DOTNET_ROOT=/snap/dotnet-sdk/current" | tee -a /tmp/deploy_server.sh
+        ;;
+    (sles)
+        echo "export DOTNET_ROOT=$${DOTNET_INSTALL_DIR}" | tee -a /tmp/deploy_server.sh
+        export DOTNET_ROOT=$${DOTNET_INSTALL_DIR}
         ;;
       (rhel*)
         ;;
     esac
+
+    export PATH="$${PATH}":"$${ansible_bin}":"$${tf_bin}":"$${DOTNET_ROOT}"
+
 
     # Set env for MSI
     (echo export ARM_USE_MSI=true | sudo tee -a /etc/profile.d/deploy_server.sh) > /dev/null 2>&1
@@ -638,14 +691,13 @@ else
 
     # Add new /opt bin directories to start of PATH to ensure the versions we installed
     # are preferred over any installed standard system versions.
-    echo export "PATH=$${ansible_bin}:$${tf_bin}:"$PATH:'$HOME/Azure_SAP_Automated_Deployment/sap-automation/deploy/scripts' | sudo tee -a /etc/profile.d/deploy_server.sh
+    echo export "PATH=$${ansible_bin}:$${tf_bin}:"'$${PATH}'::"$${DOTNET_ROOT}":'$${HOME}/Azure_SAP_Automated_Deployment/sap-automation/deploy/scripts' | sudo tee -a /etc/profile.d/deploy_server.sh
 
     # Ensure that the user's account is logged in to Azure with specified creds
     echo az login --identity --allow-no-subscriptions --output none | sudo tee -a /etc/profile.d/deploy_server.sh
     echo 'echo $${USER} account ready for use with Azure SAP Automated Deployment' | sudo tee -a /etc/profile.d/deploy_server.sh
 
-
-    sudo runuser -l "$${local_user}" -c 'az login --identity --allow-no-subscriptions --output none'
+    sudo runuser -l "$${local_user}" -c '/usr/bin/az login --identity --allow-no-subscriptions --output none'
 
     #
     # Create Agent
@@ -707,10 +759,30 @@ else
         sudo rm "$${agent_home}/config_fixed_params.sh"
 
         sudo touch "$${agent_home}/agent_configured"
+
+
+        # Install dotNet
+        case "$(get_distro_name)" in
+          (ubuntu)
+              sudo snap install dotnet-sdk --classic --channel=7.0
+              sudo snap alias dotnet-sdk.dotnet dotnet
+              ;;
+          (sles)
+              # sudo rpm -Uvh https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm
+              # sudo ln --force -s /etc/yum.repos.d/microsoft-prod.repo /etc/zypp/repos.d/microsoft-prod.repo
+              # sudo zypper install dotnet-sdk-7.0
+              sudo wget https://dot.net/v1/dotnet-install.sh -O "/home/$${local_user}/dotnet-install.sh"
+              sudo chmod +x "/home/$${local_user}/dotnet-install.sh"
+              sudo /home/$${local_user}/dotnet-install.sh --install-dir "$${DOTNET_ROOT}" --channel 7.0
+              ;;
+          (rhel*)
+            sudo dnf install dotnet-sdk-7.0 -y
+            ;;
+        esac
       else
-        echo "export SAP_AUTOMATION_REPO_PATH='$HOME/Azure_SAP_Automated_Deployment/sap-automation'" | sudo tee -a /etc/profile.d/deploy_server.sh
-        echo "export DEPLOYMENT_REPO_PATH='$HOME/Azure_SAP_Automated_Deployment/sap-automation'" | sudo tee -a /etc/profile.d/deploy_server.sh
-        echo "export CONFIG_REPO_PATH='$HOME/Azure_SAP_Automated_Deployment/WORKSPACES'" | sudo tee -a /etc/profile.d/deploy_server.sh
+        echo "export SAP_AUTOMATION_REPO_PATH='$${HOME}/Azure_SAP_Automated_Deployment/sap-automation'" | sudo tee -a /etc/profile.d/deploy_server.sh
+        echo "export DEPLOYMENT_REPO_PATH='$${HOME}/Azure_SAP_Automated_Deployment/sap-automation'" | sudo tee -a /etc/profile.d/deploy_server.sh
+        echo "export CONFIG_REPO_PATH='$${HOME}/Azure_SAP_Automated_Deployment/WORKSPACES'" | sudo tee -a /etc/profile.d/deploy_server.sh
       fi
     fi
 fi
