Control Plane update

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -89,52 +89,6 @@ stages:
                 cd $HOME; mkdir -p .sap_deployment_automation
                 echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
 
-              echo -e "$green--- Validations ---$reset"
-                if [ ! -f DEPLOYER/$(deployerfolder)/$(deployerconfig) ]; then
-                  echo -e "$boldred--- File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found ---$reset"
-                  echo "##vso[task.logissue type=error]File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found."
-                  exit 2
-                fi
-                if [ ! -f LIBRARY/$(libraryfolder)/$(libraryconfig) ]; then
-                  echo -e "$boldred--- File LIBRARY/$(libraryfolder)/$(libraryconfig)  was not found ---$reset"
-                  echo "##vso[task.logissue type=error]File LIBRARY/$(libraryfolder)/$(libraryconfig) was not found."
-                  exit 2
-                fi
-                if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-                  exit 2
-                fi
-                if [ ! -n $(ARM_CLIENT_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-                  exit 2
-                fi
-                if [ ! -n $ARM_CLIENT_SECRET ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-                  exit 2
-                fi
-                if [ ! -n $(ARM_TENANT_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-                  exit 2
-                fi
-                if [ $(use_webapp) ]; then
-                  echo "Use WebApp is selected"
-                  if [ -z $(APP_REGISTRATION_APP_ID) ]; then
-                    echo "##vso[task.logissue type=error]Variable APP_REGISTRATION_APP_ID was not defined."
-                    exit 2
-                  
-                  fi
-                  if [ -z $(WEB_APP_CLIENT_SECRET) ]; then
-                    echo "##vso[task.logissue type=error]Variable WEB_APP_CLIENT_SECRET was not defined."
-                    exit 2
-                  fi
-                fi
-
-              echo -e "$green--- Pull the latest content from DevOps ---$reset"
-                git config --global user.email "$(Build.RequestedForEmail)"
-                git config --global user.name "$(Build.RequestedFor)"
-                git checkout -q $(Branch)
-                git pull
-
               echo -e "$green--- Configure devops CLI extension ---$reset"
                 az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
                 az devops configure -d organization=$(System.CollectionUri)
@@ -155,6 +109,61 @@ stages:
 
                 fi
 
+              echo -e "$green--- Validations ---$reset"
+                if [ ! -f DEPLOYER/$(deployerfolder)/$(deployerconfig) ]; then
+                  echo -e "$boldred--- File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found ---$reset"
+                  echo "##vso[task.logissue type=error]File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found."
+                  exit 2
+                fi
+
+                if [ ! -f LIBRARY/$(libraryfolder)/$(libraryconfig) ]; then
+                  echo -e "$boldred--- File LIBRARY/$(libraryfolder)/$(libraryconfig)  was not found ---$reset"
+                  echo "##vso[task.logissue type=error]File LIBRARY/$(libraryfolder)/$(libraryconfig) was not found."
+                  exit 2
+                fi
+
+                if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                  exit 2
+                fi
+
+                if [ ! -n $(ARM_CLIENT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                  exit 2
+                fi
+
+                if [ ! -n $ARM_CLIENT_SECRET ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                  exit 2
+                fi
+
+                if [ ! -n $(ARM_TENANT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                  exit 2
+                fi
+
+                if [ $(use_webapp) == "True" ]; then
+                  echo "Use WebApp is selected"
+
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "APP_REGISTRATION_APP_ID")
+                  if [  -z "${az_var}" ]; then
+                    echo "##vso[task.logissue type=error]Variable APP_REGISTRATION_APP_ID was not defined."
+                    exit 2
+                  fi
+                  
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "WEB_APP_CLIENT_SECRET")
+                  if [ -z "${az_var}" ]; then
+                    echo "##vso[task.logissue type=error]Variable WEB_APP_CLIENT_SECRET was not defined."
+                    exit 2
+                  fi
+                fi
+
+              echo -e "$green--- Pull the latest content from DevOps ---$reset"
+                git config --global user.email "$(Build.RequestedForEmail)"
+                git config --global user.name "$(Build.RequestedFor)"
+                git checkout -q $(Branch)
+                git pull
+
               echo -e "$green--- Convert config files to UX format ---$reset"
                 sudo apt-get -qq install dos2unix
                 dos2unix -q DEPLOYER/$(deployerfolder)/$(deployerconfig)
@@ -163,7 +172,7 @@ stages:
               echo -e "$green--- Exporting webapp variables ---$reset"
                 export IS_PIPELINE_DEPLOYMENT=true
                 export TF_VAR_use_webapp=$(use_webapp)
-                if [ $(use_webapp) == "true" ]; then
+                if [ $(use_webapp) == "True" ]; then
                   az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "APP_REGISTRATION_APP_ID")
                   if [ ! -z "${az_var}" ]; then
                     export TF_VAR_app_registration_app_id=$(APP_REGISTRATION_APP_ID); echo 'App ID' "${TF_VAR_app_registration_app_id}"
@@ -174,6 +183,8 @@ stages:
                     export TF_VAR_webapp_client_secret=$(WEB_APP_CLIENT_SECRET); echo 'Secret' "${TF_VAR_webapp_client_secret}"
                   fi
                 fi
+
+              echo -e "$green--- Configuring variables ---$reset"
               
               deployer_environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}$LOCATION
 
