Pipeline updates

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -53,8 +53,10 @@ variables:
     value:                             logfile_$(Build.BuildId)
   - name:                              tf_url
     value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip
+
   - name:                              this_agent
     value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]
+
   - name:                              REMOTE_STATE_SA
     value:                             $[variables['Terraform_Remote_Storage_Account_Name']]
   - name:                              REMOTE_STATE_RG
@@ -89,7 +91,11 @@ stages:
                     echo "Agent: " $(this_agent)
 
                 echo -e "$green--- Configure devops CLI extension ---$reset"
-                    az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                    devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                    if [ -z "$devops_extension_installed" ]; then
+                      az extension add --name azure-devops --output none
+                    fi
+
                     az devops configure -d organization=$(System.CollectionUri)
                     az devops configure -d project=$(System.TeamProject)
                     export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
@@ -100,11 +106,11 @@ stages:
                     fi
                 echo -e "$green--- Variables ---$reset"
 
-                    if [ -n $(POOL) ]; then
-                       export POOL_NAME=$(az pipelines pool list --query "[?name=='$(POOL)'].name | [0]")
+                    if [ -n $TF_VAR_agent_pool ]; then
+                       export POOL_NAME=$(az pipelines pool list --query "[?name=='$TF_VAR_agent_pool'].name | [0]")
                        echo POOL ${POOL_NAME}
                        if [ -z ${POOL_NAME} ]; then
-                           echo "##vso[task.logissue type=error]Agent Pool $(POOL) does not exist."
+                           echo "##vso[task.logissue type=error]Agent Pool $TF_VAR_agent_pool does not exist."
                            exit 2
                        fi
 
@@ -183,17 +189,6 @@ stages:
                     mkdir -p .sap_deployment_automation
                     echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH >.sap_deployment_automation/config
 
-                echo -e "$green--- Install Terraform ---$reset"
-                    wget -q $(tf_url)
-                    return_code=$?
-                    if [ 0 != $return_code ]; then
-                        echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-                        exit 2
-                    fi
-                    unzip -qq terraform_$(tf_version)_linux_amd64.zip
-                    sudo mv terraform /bin/
-                    rm terraform_$(tf_version)_linux_amd64.zip
-
                 echo -e "$green--- File Validations ---$reset"
                     if [ ! -f DEPLOYER/$(deployerfolder)/$(deployerconfig) ]; then
                         echo -e "$boldred--- File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found ---$reset"
@@ -207,6 +202,22 @@ stages:
                         exit 2
                     fi
 
+                if [[ "azure pipelines" == $(this_agent) ]]; then
+                    echo -e "$green --- Install dos2unix ---$reset"
+                    sudo apt-get -qq install dos2unix
+
+                    echo -e "$green --- Install terraform ---$reset"
+    
+                    wget -q $(tf_url)
+                    return_code=$?
+                    if [ 0 != $return_code ]; then
+                        echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                        exit 2
+                    fi
+                    unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+                    rm -f terraform_$(tf_version)_linux_amd64.zip
+                fi
+
                 echo -e "$green--- Pull the latest content from DevOps ---$reset"
                     git config --global user.email "$(Build.RequestedForEmail)"
                     git config --global user.name "$(Build.RequestedFor)"
@@ -214,7 +225,6 @@ stages:
                     git pull
 
                     echo -e "$green--- Convert config files to UX format ---$reset"
-                    sudo apt-get -qq install dos2unix
                     dos2unix -q DEPLOYER/$(deployerfolder)/$(deployerconfig)
                     dos2unix -q LIBRARY/$(libraryfolder)/$(libraryconfig)
 
@@ -411,7 +421,7 @@ stages:
 
             displayName:                      Deploy control plane
             env:
-              SYSTEM_ACCESSTOKEN:             $(System.AccessToken)
+              SYSTEM_ACCESSTOKEN:             
               ARM_SUBSCRIPTION_ID:            $(ARM_SUBSCRIPTION_ID)
               ARM_CLIENT_ID:                  $(ARM_CLIENT_ID)
               ARM_CLIENT_SECRET:              $(ARM_CLIENT_SECRET)
diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -129,10 +129,9 @@ stages:
               echo "##vso[build.updatebuildnumber]Deploying the SAP Workload zone defined in $(workload_zone_folder)"
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
 
-              echo $key_vault
               echo -e "$green--- Validations ---$reset"
 
-                if [ -z ${ARM_SUBSCRIPTION_ID} ]; then
+                if [ -z $ARM_SUBSCRIPTION_ID ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
                   exit 2
                 fi
@@ -160,14 +159,13 @@ stages:
 
                 cd $HOME; mkdir -p .sap_deployment_automation
 
-              echo -e "$green --- Install dos2unix ---$reset"
-                sudo apt-get -qq install dos2unix
-
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                if [ -z "$devops_extension_installed" ]; then
+                  az extension add --name azure-devops --output none
+                fi
                 az devops configure -d organization=$(System.CollectionUri)
                 az devops configure -d project=$(System.TeamProject)
-                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
 
                 export PARENT_VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(parent_variable_group)'].id | [0]")
                 echo '$(parent_variable_group) id: ' $PARENT_VARIABLE_GROUP_ID
@@ -246,8 +244,8 @@ stages:
                   echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
                   exit 2
                 else
-                  export ARM_SUBSCRIPTION_ID=${az_var}  ; echo 'Target subscription' $ARM_SUBSCRIPTION_ID
-                  
+                  echo 'Target subscription' $ARM_SUBSCRIPTION_ID
+
                 fi
 
                 az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Workload_Key_Vault.value" | tr -d \")
@@ -260,21 +258,39 @@ stages:
                 fi
 
               echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
 
-              echo -e "$green--- Install Terraform ---$reset"
+              secrets_set=1
 
-                wget -q $(tf_url)
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-                  exit 2
-                fi
-                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
-                rm -f terraform_$(tf_version)_linux_amd64.zip
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                  sudo apt-get -qq install dos2unix
+
+                echo -e "$green --- Install terraform ---$reset"
+
+                  wget -q $(tf_url)
+                  return_code=$?
+                  if [ 0 != $return_code ]; then
+                    echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                    exit 2
+                  fi
+                  unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+                  rm -f terraform_$(tf_version)_linux_amd64.zip
+              else
+                echo -e "$green --- Set secrets ---$reset"
+
+                  az login --identity --allow-no-subscriptions --output none
+                  $DEPLOYMENT_REPO_PATH/deploy/scripts/set_secrets.sh --workload --vault "${key_vault}"      \
+                   --environment "${ENVIRONMENT}" --region "${LOCATION}" --subscription $ARM_SUBSCRIPTION_ID \
+                  --spn_id $ARM_CLIENT_ID --spn_secret $ARM_CLIENT_SECRET --tenant_id $ARM_TENANT_ID
+                  secrets_set=$? ; echo "Set Secrets returned $secrets_set"
+
+              fi
 
               echo -e "$green--- az login ---$reset"
                 az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
+                resource_group_name=$(az keyvault show --name "${key_vault}" --query resourceGroup | tr -d \")
+                az keyvault set-policy --name "${key_vault}" --resource-group $resource_group_name --spn $ARM_CLIENT_ID --secret-permissions get list --output none
+
                 return_code=$?
                 if [ 0 != $return_code ]; then
                   echo -e "$boldred--- Login failed ---$reset"
@@ -284,12 +300,11 @@ stages:
 
                 ip_added_workload=0
 
-                az account set --subscription $(ARM_SUBSCRIPTION_ID)
-
                 if [[ "azure pipelines" == $(this_agent) ]]; then
                   this_ip=$(curl -s ipinfo.io/ip) >/dev/null 2>&1
                   echo -e "$green--- Set IP ---$reset"
                   if [ -n "${workload_key_vault}" ]; then
+                    az account set --subscription $(ARM_SUBSCRIPTION_ID)
                     az keyvault network-rule add --name ${workload_key_vault} --ip-address ${this_ip}  --output none --only-show-errors
                     ip_added_workload=1
                   fi
@@ -315,11 +330,19 @@ stages:
 
               echo -e "$green--- Deploy the workload zone ---$reset"
                 cd $HOME/LANDSCAPE/$(workload_zone_folder)
-                $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)       \
-                  --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
-                  --spn_id $ARM_CLIENT_ID --spn_secret $ARM_CLIENT_SECRET --tenant_id $ARM_TENANT_ID                                   \
-                  --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${key_vault}" --storageaccountname "${REMOTE_STATE_SA}" \
-                  --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
+
+                if [ 0 != $secrets_set ] ; then
+                  $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)       \
+                    --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
+                    --spn_id $ARM_CLIENT_ID --spn_secret $ARM_CLIENT_SECRET --tenant_id $ARM_TENANT_ID                                   \
+                    --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${key_vault}" --storageaccountname "${REMOTE_STATE_SA}" \
+                    --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
+                else
+                  $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)       \
+                    --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
+                    --deployer_tfstate_key "${deployer_tfstate_key}" --storageaccountname "${REMOTE_STATE_SA}"                           \
+                    --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
+                fi
                 return_code=$?
 
                 echo "Return code: ${return_code}"
@@ -450,5 +473,7 @@ stages:
               ARM_CLIENT_ID:           $(ARM_CLIENT_ID)
               ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
               ARM_TENANT_ID:           $(ARM_TENANT_ID)
+              AZURE_DEVOPS_EXT_PAT:    $(PAT)
+              DEPLOYMENT_REPO_PATH:    $(Build.Repository.LocalPath)
             failOnStderr:              false
 ...
diff --git a/deploy/pipelines/03-sap-system-deployment.yaml b/deploy/pipelines/03-sap-system-deployment.yaml
--- a/deploy/pipelines/03-sap-system-deployment.yaml
+++ b/deploy/pipelines/03-sap-system-deployment.yaml
@@ -78,12 +78,11 @@ stages:
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
               echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
 
-                DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-                                HOME=${DEPLOYMENT_REPO_PATH}/$(Deployment_Configuration_Path)
-                         ENVIRONMENT=$(echo $(sap_system_folder) | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENVIRONMENT
-                            LOCATION=$(echo $(sap_system_folder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCATION
-                             NETWORK=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo Network     $NETWORK
-                                 SID=$(echo $(sap_system_folder) | awk -F'-' '{print $4}' | xargs) ; echo SID         $SID
+                     HOME=${DEPLOYMENT_REPO_PATH}/$(Deployment_Configuration_Path)
+              ENVIRONMENT=$(echo $(sap_system_folder) | awk -F'-' '{print $1}' | xargs) ; echo "Environment: $ENVIRONMENT"
+                 LOCATION=$(echo $(sap_system_folder) | awk -F'-' '{print $2}' | xargs) ; echo "Location:    $LOCATION"
+                  NETWORK=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo "Network:     $NETWORK"
+                      SID=$(echo $(sap_system_folder) | awk -F'-' '{print $4}' | xargs) ; echo "SID:         $SID"
 
                 cd $HOME; mkdir -p .sap_deployment_automation
 
@@ -97,7 +96,7 @@ stages:
                   exit 2
                 fi
 
-                environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}${LOCATION}${NETWORK} ; "echo Environment file:" $environment_file_name
+                environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}${LOCATION}${NETWORK}
 
                 if [ ! -f $environment_file_name ]; then
                   echo -e "$boldred--- $ENVIRONMENT$LOCATION$NETWORK was not found ---$reset"
@@ -129,20 +128,31 @@ stages:
                   echo "##vso[task.logissue type=error]SID was not defined in the parameter file."
                   exit 2
                 fi
-              echo -e "$green--- Install Terraform ---$reset"
-                wget -q $(tf_url)
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-                  exit 2
-                fi
-                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
-                rm -f terraform_$(tf_version)_linux_amd64.zip
+
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                  sudo apt-get -qq install dos2unix
+
+                echo -e "$green --- Install terraform ---$reset"
+  
+                  wget -q $(tf_url)
+                  return_code=$?
+                  if [ 0 != $return_code ]; then
+                    echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                    exit 2
+                  fi
+                  unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+                  rm -f terraform_$(tf_version)_linux_amd64.zip
+              fi
+
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                if [ -z "$devops_extension_installed" ]; then
+                  az extension add --name azure-devops --output none
+                fi
                 az devops configure -d organization=$(System.CollectionUri)
                 az devops configure -d project=$(System.TeamProject)
-                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
+                
                 export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
                 echo VARIABLE_GROUP_ID ${VARIABLE_GROUP_ID}
               echo -e "$green--- Pull the latest content from DevOps ---$reset"
@@ -152,26 +162,25 @@ stages:
                 git pull
               echo -e "$green--- --- Convert config file to UX format ---$reset"
 
-                sudo apt-get -qq install dos2unix
                 dos2unix -q SYSTEM/$(sap_system_folder)/$(sap_system_configuration)
 
               echo -e "$green--- Define variables ---$reset"
                 cd $HOME/SYSTEM/$(sap_system_folder)
 
                 if [ -z $(REMOTE_STATE_SA) ]; then
-                  export REMOTE_STATE_SA=$(cat ${deployer_environment_file_name}      | grep REMOTE_STATE_SA      | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file storage account' $REMOTE_STATE_SA
+                  export REMOTE_STATE_SA=$(cat ${environment_file_name}      | grep REMOTE_STATE_SA      | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file storage account' $REMOTE_STATE_SA
                 fi
 
                 if [ -z $(STATE_SUBSCRIPTION) ]; then
-                  export STATE_SUBSCRIPTION=$(cat ${deployer_environment_file_name}   | grep STATE_SUBSCRIPTION   | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
+                  export STATE_SUBSCRIPTION=$(cat ${environment_file_name}   | grep STATE_SUBSCRIPTION   | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
                 fi
 
                 if [ -z $(deployer_tfstate_key) ]; then
-                  export deployer_tfstate_key=$(cat ${deployer_environment_file_name} | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
+                  export deployer_tfstate_key=$(cat ${environment_file_name} | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
                 fi
 
                 if [ -z $(key_vault) ]; then
-                  export key_vault=$(cat ${deployer_environment_file_name}            | grep keyvault=            | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
+                  export key_vault=$(cat ${environment_file_name}            | grep keyvault=            | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
                 fi
 
                 az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "${NETWORK}"Workload_Zone_State_FileName.value)  | tr -d \"
@@ -316,5 +325,6 @@ stages:
               SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
               DEPLOYMENT_REPO_PATH:    $(Build.Repository.LocalPath)
               AZURE_DEVOPS_EXT_PAT:    $(System.AccessToken)
+                
             failOnStderr:              false
 ...
diff --git a/deploy/pipelines/05-DB-and-SAP-installation.yaml b/deploy/pipelines/05-DB-and-SAP-installation.yaml
--- a/deploy/pipelines/05-DB-and-SAP-installation.yaml
+++ b/deploy/pipelines/05-DB-and-SAP-installation.yaml
@@ -13,12 +13,12 @@ parameters:
   - name:                              sap_system_configuration_name
     displayName:                       "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
     type:                              string
-    default:                           PRD-UKSO-SAP07-RHB
+    default:                           DEV-WEEU-SAP01-X00
 
   - name:                              environment
     displayName:                       Workload Environment (DEV, QUA, PRD, ...)
     type:                              string
-    default:                           PRD
+    default:                           DEV
 
   - name:                              bom_base_name
     displayName:                       Bill of Materials name
@@ -125,14 +125,20 @@ stages:
           - bash: |
               #!/bin/bash
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                  sudo apt-get -qq install dos2unix
+              fi
               echo -e "$green--- --- Convert config file to UX format ---$reset"
-                sudo apt-get -qq install dos2unix
               echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
                 export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
                 cd $HOME
 
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                if [ -z "$devops_extension_installed" ]; then
+                  az extension add --name azure-devops --output none
+                fi
                 az devops configure -d organization=$(System.CollectionUri)
                 az devops configure -d project=$(System.TeamProject)
                 export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
@@ -154,7 +160,7 @@ stages:
                           params_file=$HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml              ;  echo sap_parameters_file $params_file
 
               if [[ "azure pipelines" == $(this_agent) ]]; then
-                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-${ENVIRONMENT} variable group"
+                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-${ENVIRONMENT} variable group using the 'POOL' variable."
                   exit 2
                 fi
 
@@ -193,35 +199,6 @@ stages:
                 echo "##vso[task.setvariable variable=HOSTS;isOutput=true]${SID}_hosts.yaml"
                 echo "##vso[task.setvariable variable=CONFIGURATION_NAME;isOutput=true]$(sap_system_folder)"
 
-              echo -e "$green--- az login ---$reset"
-                if [ -z $(ARM_SUBSCRIPTION_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-                  exit 2
-                fi
-
-                if [ -z $(ARM_CLIENT_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-                  exit 2
-                fi
-
-                if [ -z $(ARM_CLIENT_SECRET) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-                  exit 2
-                fi
-
-                if [ -z $(ARM_TENANT_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-                  exit 2
-                fi
-
-                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID) --output none
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo -e "$boldred--- Login failed ---$reset"
-                  echo "##vso[task.logissue type=error]az login failed."
-                  exit $return_code
-                fi
-                az account set --subscription $(ARM_SUBSCRIPTION_ID)
               echo -e "$green--- Get Files from the DevOps Repository ---$reset"
                 cd $(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)
                 sap_params_updated=0
@@ -240,6 +217,15 @@ stages:
                   export workload_key_vault=${az_var} ; echo 'Workload Key Vault' ${workload_key_vault}
                 fi
 
+              echo -e "$green--- az login ---$reset"
+
+                az login --identity --allow-no-subscriptions --output none
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo -e "$boldred--- Login failed ---$reset"
+                  echo "##vso[task.logissue type=error]az login failed."
+                  exit $return_code
+                fi
                 az keyvault secret show --name ${ENVIRONMENT}-${LOCATION}-${NETWORK}-sid-sshkey --vault-name $workload_key_vault --query value -o tsv > artifacts/$(sap_system_folder)_sshkey
                 cp sap-parameters.yaml artifacts/.
                 cp ${SID}_hosts.yaml artifacts/.
@@ -265,6 +251,8 @@ stages:
             displayName:               Preparation for Ansible
             env:
               SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
+              ARM_SUBSCRIPTION_ID:     $(ARM_SUBSCRIPTION_ID)
+              ANSIBLE_HOST_KEY_CHECKING: false
             failOnStderr:              true
           - publish:                   $(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)/artifacts
             artifact:                  ansible_data
@@ -312,6 +300,7 @@ stages:
 
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -361,7 +350,7 @@ stages:
 
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
-              ANSIBLE_HOST_KEY_CHECKING: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               DEPLOYMENT_REPO_PATH:    $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
@@ -408,6 +397,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -457,6 +447,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -508,6 +499,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -579,6 +571,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -654,6 +647,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -726,6 +720,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
@@ -782,6 +777,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
 
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
@@ -859,6 +855,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
 
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
@@ -926,6 +923,7 @@ stages:
               failOnStderr:            false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+              ANSIBLE_HOST_KEY_CHECKING:     false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
diff --git a/deploy/pipelines/10-remover-terraform.yaml b/deploy/pipelines/10-remover-terraform.yaml
--- a/deploy/pipelines/10-remover-terraform.yaml
+++ b/deploy/pipelines/10-remover-terraform.yaml
@@ -58,7 +58,7 @@ parameters:
 trigger:                               none
 
 pool:
-  name:                                $[coalesce(variables['POOL'], variables['Agent'])]
+  name:                                $(Agent)
 
 variables:
   - group:                             "SDAF-General"
@@ -164,7 +164,10 @@ stages:
                 fi
 
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                if [ -z "$devops_extension_installed" ]; then
+                  az extension add --name azure-devops --output none
+                fi
                 export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
 
                 az devops configure -d organization=$(System.CollectionUri)
@@ -182,6 +185,21 @@ stages:
                     exit 2
                 fi
 
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                  sudo apt-get -qq install dos2unix
+
+                echo -e "$green --- Install terraform ---$reset"
+  
+                  wget -q $(tf_url)
+                  return_code=$?
+                  if [ 0 != $return_code ]; then
+                    echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                    exit 2
+                  fi
+                  unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+                  rm -f terraform_$(tf_version)_linux_amd64.zip
+              fi
               echo -e "$green--- Set variables ---$reset"
                 echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
 
@@ -205,18 +223,8 @@ stages:
                 fi
 
               echo -e "$green--- --- Convert config file to UX format ---$reset"
-                sudo apt-get -qq install dos2unix
                 dos2unix -q SYSTEM/$(sap_system_folder)/$(sap_system_configuration)
 
-              echo -e "$green--- Install Terraform ---$reset"
-                wget -q $(tf_url)
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-                  exit 2
-                fi
-                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
-                rm -f terraform_$(tf_version)_linux_amd64.zip
 
               echo -e "$green--- az login ---$reset"
                 az login --service-principal --username $(ARM_CLIENT_ID) --password $ARM_CLIENT_SECRET --tenant $(ARM_TENANT_ID) --output none
@@ -358,6 +366,21 @@ stages:
               
               cd $HOME; mkdir -p .sap_deployment_automation
               workload_environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}$LOCATION$NETWORK
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                  sudo apt-get -qq install dos2unix
+
+                echo -e "$green --- Install terraform ---$reset"
+  
+                  wget -q $(tf_url)
+                  return_code=$?
+                  if [ 0 != $return_code ]; then
+                    echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                    exit 2
+                  fi
+                  unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+                  rm -f terraform_$(tf_version)_linux_amd64.zip
+              fi
 
               echo -e "$green--- Validations ---$reset"
 
@@ -386,7 +409,10 @@ stages:
                   fi
                 fi
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                if [ -z "$devops_extension_installed" ]; then
+                  az extension add --name azure-devops --output none
+                fi
                 export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
 
                 az devops configure -d organization=$(System.CollectionUri)
@@ -440,16 +466,6 @@ stages:
                   STATE_SUBSCRIPTION=$(cat ${workload_environment_file_name}  | grep STATE_SUBSCRIPTION   | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
                 fi
 
-              echo -e "$green--- Install Terraform ---$reset"
-                wget -q $(tf_url)
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-                  exit 2
-                fi
-                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
-                rm -f terraform_$(tf_version)_linux_amd64.zip
-
               echo -e "$green--- az login ---$reset"
 
                 az login --service-principal --username $(ARM_CLIENT_ID) --password $ARM_CLIENT_SECRET --tenant $(ARM_TENANT_ID) --output none
@@ -489,7 +505,6 @@ stages:
                 fi
 
               echo -e "$green--- --- Convert config file to UX format ---$reset"
-                sudo apt-get -qq install dos2unix
                 dos2unix -q LANDSCAPE/$(workload_zone_folder)/$(workload_zone_configuration_file)
               echo -e "$green--- Pull latest ---$reset"
                 git config --global user.email "$(Build.RequestedForEmail)"
@@ -616,7 +631,10 @@ stages:
                 cd $HOME; mkdir -p .sap_deployment_automation
                 echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                if [ -z "$devops_extension_installed" ]; then
+                  az extension add --name azure-devops --output none
+                fi
                 if [ -n $(PAT) ]; then
                   export AZURE_DEVOPS_EXT_PAT=$(PAT)
                 else
@@ -633,8 +651,23 @@ stages:
                     exit 2
                 fi
 
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo -e "$green --- Install dos2unix ---$reset"
+                  sudo apt-get -qq install dos2unix
+
+                echo -e "$green --- Install terraform ---$reset"
+  
+                  wget -q $(tf_url)
+                  return_code=$?
+                  if [ 0 != $return_code ]; then
+                    echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                    exit 2
+                  fi
+                  unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+                  rm -f terraform_$(tf_version)_linux_amd64.zip
+              fi
+
               echo -e "$green--- Convert config files to UX format ---$reset"
-                sudo apt-get -qq install dos2unix
                 dos2unix -q DEPLOYER/$(deployer_folder)/$(deployer_configuration_file) 2> /dev/null
                 dos2unix -q LIBRARY/$(library_folder)/$(library_configuration_file)    2> /dev/null
 
