Pipeline updates - better error handling

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -55,6 +55,14 @@ variables:
     value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip
   - name:                              this_agent
     value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]
+  - name:                              REMOTE_STATE_SA
+    value:                             $[variables['Terraform_Remote_Storage_Account_Name']]
+  - name:                              REMOTE_STATE_RG
+    value:                             $[variables['Terraform_Remote_Storage_Resource_Group_Name']]
+  - name:                              deployer_tfstate_key
+    value:                             $[variables['Deployer_State_FileName']]
+  - name:                              keyvault
+    value:                             $[variables['Deployer_Key_Vault']]
 
 stages:
   - stage:                             Deploy_controlplane
@@ -86,6 +94,11 @@ stages:
                     az devops configure -d project=$(System.TeamProject)
                     export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
                     echo VARIABLE_GROUP_ID ${VARIABLE_GROUP_ID}
+                    if [ -z ${VARIABLE_GROUP_ID} ]; then
+                        echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
+                        exit 2
+                    fi
+                echo -e "$green--- Variables ---$reset"
 
                     if [ -n $(POOL) ]; then
                        export POOL_NAME=$(az pipelines pool list --query "[?name=='$(POOL)'].name | [0]")
@@ -134,43 +147,38 @@ stages:
                     fi
 
                     deployer_environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}${LOCATION}
+                    bootstrapped=0
 
-                    if [ ! -f $deployer_environment_file_name ]; then
+                    if [ ! -f $deployer_environment_file_name ]; then # Line 74
 
-                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
-                        if [ -n ${az_var} ]; then
-                            echo "REMOTE_STATE_SA = "$(Terraform_Remote_Storage_Account_Name) | tee -a  $deployer_environment_file_name > /dev/null
+                        if [ $(REMOTE_STATE_SA) ]; then
+                            echo "REMOTE_STATE_SA="$(REMOTE_STATE_SA)
+                            echo "REMOTE_STATE_SA="$(REMOTE_STATE_SA) | tee -a  $deployer_environment_file_name > /dev/null
+                            echo "step=3" | tee -a  $deployer_environment_file_name > /dev/null
                         fi
 
-                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Resource_Group_Name.value")
-                        if [ -n ${az_var} ]; then
-                            echo "REMOTE_STATE_RG = "$(Terraform_Remote_Storage_Resource_Group_Name) | tee -a  $deployer_environment_file_name > /dev/null
+                        if [ $(REMOTE_STATE_RG) ]; then
+                            echo "REMOTE_STATE_RG="$(REMOTE_STATE_RG)
+                            echo "REMOTE_STATE_RG="$(REMOTE_STATE_RG) | tee -a  $deployer_environment_file_name > /dev/null
                         fi
 
-                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "ARM_SUBSCRIPTION_ID.value")
-                        if [ -n ${az_var} ]; then
-                            echo "subscription = "$(ARM_SUBSCRIPTION_ID) | tee -a  $deployer_environment_file_name > /dev/null
-                            echo "REMOTE_STATE_RG = "$(ARM_SUBSCRIPTION_ID) | tee -a  $deployer_environment_file_name > /dev/null
-                            echo "STATE_SUBSCRIPTION = "$(ARM_SUBSCRIPTION_ID) | tee -a  $deployer_environment_file_name > /dev/null
+                        if [ -n "$subscription" ]; then
+                            echo "subscription="$subscription | tee -a  $deployer_environment_file_name > /dev/null
+                            echo "STATE_SUBSCRIPTION="$subscription | tee -a  $deployer_environment_file_name > /dev/null
                         fi
 
-
-                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value")
-                        if [ -n ${az_var} ]; then
-                            echo "deployer_tfstate_key=" $(Deployer_State_FileName)  | tee -a  $deployer_environment_file_name > /dev/null
+                        if [ $(deployer_tfstate_key) ]; then
+                            echo "deployer_tfstate_key="$(deployer_tfstate_key)  | tee -a  $deployer_environment_file_name > /dev/null
                         fi
 
-                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value")
-                        if [ -z ${az_var} ]; then
-                            echo "keyvault=" $(Deployer_Key_Vault)  | tee -a  $deployer_environment_file_name > /dev/null
+                        if [ $(keyvault) ]; then
+                            echo "keyvault="$(keyvault)  | tee -a  $deployer_environment_file_name > /dev/null
+                            bootstrapped=1
                         fi
-                        echo "step=3" | tee -a  $deployer_environment_file_name > /dev/null
 
                     fi
 
                 echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-
-
                     cd $HOME
                     mkdir -p .sap_deployment_automation
                     echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH >.sap_deployment_automation/config
@@ -217,17 +225,19 @@ stages:
                     export key_vault=""
 
                     if [ -f ${deployer_environment_file_name} ]; then
-                       export key_vault=$(cat ${deployer_environment_file_name} | grep key_vault | awk -F'=' '{print $2}' | xargs) ; echo "Key Vault: $key_vault"
-                       if [ -n "${key_vault}" ]; then
-                          echo 'Deployer Key Vault' ${key_vault}
-                          ip_added=0
+                        if [ 0 == $bootstrapped ]; then
+                            export key_vault=$(cat ${deployer_environment_file_name} | grep key_vault | awk -F'=' '{print $2}' | xargs) ; echo "Key Vault: $key_vault"
+                            if [ -n "${key_vault}" ]; then
+                                echo 'Deployer Key Vault' ${key_vault}
+                                ip_added=0
 
-                          if [[ "azure pipelines" == $(this_agent) ]]; then
-                            this_ip=$(curl -s ipinfo.io/ip) >/dev/null 2>&1
-                            az keyvault network-rule add --name ${key_vault} --ip-address ${this_ip} --only-show-errors --output none
-                            ip_added=1
-                          fi
-                       fi
+                                if [[ "azure pipelines" == $(this_agent) ]]; then
+                                    this_ip=$(curl -s ipinfo.io/ip) >/dev/null 2>&1
+                                    az keyvault network-rule add --name ${key_vault} --ip-address ${this_ip} --only-show-errors --output none
+                                    ip_added=1
+                                fi
+                            fi
+                        fi
                     fi
 
                 echo -e "$green--- az login ---$reset"
@@ -253,9 +263,8 @@ stages:
                     fi
 
                     storage_account_parameter=""
-                    az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
-                    if [ -n ${az_var} ]; then
-                       storage_account_parameter='--storageaccountname $(Terraform_Remote_Storage_Account_Name)'
+                    if [ -n "${REMOTE_STATE_SA}" ]; then
+                       storage_account_parameter='--storageaccountname $(REMOTE_STATE_SA)'
                     fi
 
                     $DEPLOYMENT_REPO_PATH/deploy/scripts/deploy_controlplane.sh               \
@@ -298,17 +307,17 @@ stages:
 
                     if [ -f ${deployer_environment_file_name} ]; then
 
-                       deployer_tfstate_key=$(cat ${deployer_environment_file_name} | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs)
-                       echo 'Deployer State File' $deployer_tfstate_key
+                       file_deployer_tfstate_key=$(cat ${deployer_environment_file_name} | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs)
+                       echo 'Deployer State File' $file_deployer_tfstate_key
 
-                       key_vault=$(cat ${deployer_environment_file_name} | grep keyvault= | awk -F'=' '{print $2}' | xargs)
-                       echo 'Deployer Key Vault' ${key_vault}
+                       file_key_vault=$(cat ${deployer_environment_file_name} | grep keyvault= | awk -F'=' '{print $2}' | xargs)
+                       echo 'Deployer Key Vault' ${file_key_vault}
 
-                       REMOTE_STATE_SA=$(cat ${deployer_environment_file_name} | grep REMOTE_STATE_SA | awk -F'=' '{print $2}' | xargs)
-                       echo 'Terraform state file storage account' $REMOTE_STATE_SA
+                       file_REMOTE_STATE_SA=$(cat ${deployer_environment_file_name} | grep REMOTE_STATE_SA | awk -F'=' '{print $2}' | xargs)
+                       echo 'Terraform state file storage account' $file_REMOTE_STATE_SA
 
-                       REMOTE_STATE_RG=$(cat ${deployer_environment_file_name} | grep REMOTE_STATE_RG | awk -F'=' '{print $2}' | xargs)
-                       echo 'Terraform state file resource group' $REMOTE_STATE_RG
+                       file_REMOTE_STATE_RG=$(cat ${deployer_environment_file_name} | grep REMOTE_STATE_RG | awk -F'=' '{print $2}' | xargs)
+                       echo 'Terraform state file resource group' $file_REMOTE_STATE_RG
                     fi
 
                 echo -e "$green--- Update repo ---$reset"
@@ -362,39 +371,41 @@ stages:
                     fi
 
                 echo -e "$green--- Adding variables to the variable group:" $(variable_group) "---$reset"
-                    az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
-                    if [ -z ${az_var} ]; then
-                        az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value $REMOTE_STATE_SA --output none --only-show-errors
-                    else
-                        az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value $REMOTE_STATE_SA --output none --only-show-errors
-                    fi
+                    if [ 0 == $return_code ]; then
+                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
+                        if [ -z ${az_var} ]; then
+                            az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value ${file_REMOTE_STATE_SA} --output none --only-show-errors
+                        else
+                            az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value ${file_REMOTE_STATE_SA} --output none --only-show-errors
+                        fi
 
-                    az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Resource_Group_Name.value")
-                    if [ -z ${az_var} ]; then
-                        az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Resource_Group_Name --value $REMOTE_STATE_RG --output none --only-show-errors
-                    else
-                        az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Resource_Group_Name --value $REMOTE_STATE_RG --output none --only-show-errors
-                    fi
+                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Resource_Group_Name.value")
+                        if [ -z ${az_var} ]; then
+                            az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Resource_Group_Name --value ${file_REMOTE_STATE_RG} --output none --only-show-errors
+                        else
+                            az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Resource_Group_Name --value ${file_REMOTE_STATE_RG} --output none --only-show-errors
+                        fi
 
-                    az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Subscription.value")
-                    if [ -z ${az_var} ]; then
-                        az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value $(ARM_SUBSCRIPTION_ID) --output none --only-show-errors
-                    else
-                        az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value $(ARM_SUBSCRIPTION_ID) --output none --only-show-errors
-                    fi
+                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Subscription.value")
+                        if [ -z ${az_var} ]; then
+                            az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value $(ARM_SUBSCRIPTION_ID) --output none --only-show-errors
+                        else
+                            az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value $(ARM_SUBSCRIPTION_ID) --output none --only-show-errors
+                        fi
 
-                    az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value")
-                    if [ -z ${az_var} ]; then
-                        az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value $deployer_tfstate_key --output none --only-show-errors
-                    else
-                        az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value $deployer_tfstate_key --output none --only-show-errors
-                    fi
+                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value")
+                        if [ -z ${az_var} ]; then
+                            az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value ${file_deployer_tfstate_key} --output none --only-show-errors
+                        else
+                            az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value ${file_deployer_tfstate_key} --output none --only-show-errors
+                        fi
 
-                    az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value")
-                    if [ -z ${az_var} ]; then
-                        az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${key_vault} --output none --only-show-errors
-                    else
-                        az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${key_vault} --output none --only-show-errors
+                        az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value")
+                        if [ -z ${az_var} ]; then
+                            az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${file_key_vault} --output none --only-show-errors
+                        else
+                            az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${file_key_vault} --output none --only-show-errors
+                        fi
                     fi
                 exit $return_code
 
@@ -414,7 +425,8 @@ stages:
               IS_PIPELINE_DEPLOYMENT:         true
               TF_VAR_use_webapp:              $(use_webapp)
               DEPLOYMENT_REPO_PATH:           $(Build.Repository.LocalPath)
-
+              subscription:                   $(ARM_SUBSCRIPTION_ID)
+        
             failOnStderr:              false
 
 ...
diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -112,7 +112,6 @@ variables:
   - name:                              this_agent
     value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]
 
-
 stages:
   - stage:                             Deploy_SAP_workload_zone
     displayName:                       Deploy SAP workload zone
@@ -130,6 +129,7 @@ stages:
               echo "##vso[build.updatebuildnumber]Deploying the SAP Workload zone defined in $(workload_zone_folder)"
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
 
+              echo $key_vault
               echo -e "$green--- Validations ---$reset"
 
                 if [ -z ${ARM_SUBSCRIPTION_ID} ]; then
@@ -137,17 +137,17 @@ stages:
                   exit 2
                 fi
 
-                if [ -z ${ARM_CLIENT_ID} ]; then
+                if [ -z $ARM_CLIENT_ID ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
                   exit 2
                 fi
 
-                if [ -z ${ARM_CLIENT_SECRET} ]; then
+                if [ -z $ARM_CLIENT_SECRET ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
                   exit 2
                 fi
 
-                if [ -z ${ARM_TENANT_ID} ]; then
+                if [ -z $ARM_TENANT_ID ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
                   exit 2
                 fi
@@ -171,8 +171,18 @@ stages:
 
                 export PARENT_VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(parent_variable_group)'].id | [0]")
                 echo '$(parent_variable_group) id: ' $PARENT_VARIABLE_GROUP_ID
+                if [ -z ${PARENT_VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(parent_variable_group) could not be found."
+                    exit 2
+                fi
+
                 export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
                 echo '$(variable_group) id: ' $VARIABLE_GROUP_ID
+                if [ -z ${VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
+                    exit 2
+                fi
+
                 echo "Agent Pool: " $(this_agent)
 
               echo -e "$green--- Set DEPLOYMENT_REPO_PATH variable and ---$reset"
@@ -203,37 +213,41 @@ stages:
 
               echo -e "$green--- Read parameter values ---$reset"
 
-                if [ -n $(Deployer_State_FileName) ]; then
-                  export deployer_tfstate_key=$(Deployer_State_FileName); echo 'Deployer State File' $deployer_tfstate_key
+                az_var=$(az pipelines variable-group variable list --group-id ${PARENT_VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value" | tr -d \")
+                if [ -z ${az_var} ]; then
+                  deployer_tfstate_key=$(cat ${deployer_environment_file_name}  | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
                 else
-                  export deployer_tfstate_key=$(cat ${deployer_environment_file_name}  | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
+                  deployer_tfstate_key=${az_var} ; echo 'Deployer State File' $deployer_tfstate_key
                 fi
 
-                if [ -n $(Deployer_Key_Vault) ]; then
-                  export key_vault=$(Deployer_Key_Vault) ; echo 'Deployer Key Vault' ${key_vault}
+                az_var=$(az pipelines variable-group variable list --group-id ${PARENT_VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value" | tr -d \")
+                if [ -z ${az_var} ]; then
+                  key_vault=$(cat ${deployer_environment_file_name}  | grep keyvault= | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
                 else
-                  export key_vault=$(cat ${deployer_environment_file_name}  | grep keyvault=            | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
+                  key_vault=${az_var}; echo 'Deployer Key Vault' ${key_vault}
                 fi
 
-                if [ -n $(Terraform_Remote_Storage_Account_Name) ]; then
-                  export REMOTE_STATE_SA=$(Terraform_Remote_Storage_Account_Name)  ; echo 'Terraform state file storage account' $REMOTE_STATE_SA
+                az_var=$(az pipelines variable-group variable list --group-id ${PARENT_VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value" | tr -d \")
+                if [ -z ${az_var} ]; then
+                  REMOTE_STATE_SA=$(cat ${deployer_environment_file_name}  | grep REMOTE_STATE_SA      | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file storage account' $REMOTE_STATE_SA
                 else
-                  export REMOTE_STATE_SA=$(cat ${deployer_environment_file_name}  | grep REMOTE_STATE_SA      | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file storage account' $REMOTE_STATE_SA
+                  REMOTE_STATE_SA=${az_var}; echo 'Terraform state file storage account' $REMOTE_STATE_SA
                 fi
 
                 az_var=$(az pipelines variable-group variable list --group-id ${PARENT_VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Subscription.value" | tr -d \")
-                if [ ! -z ${az_var} ]; then
-                  export STATE_SUBSCRIPTION=${az_var}  ; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
+                if [ -z ${az_var} ]; then
+                  STATE_SUBSCRIPTION=$(cat ${deployer_environment_file_name}  | grep STATE_SUBSCRIPTION   | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
                 else
-                  export STATE_SUBSCRIPTION=$(cat ${deployer_environment_file_name}  | grep STATE_SUBSCRIPTION   | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
+                  STATE_SUBSCRIPTION=${az_var}; echo 'Terraform state file subscription' $STATE_SUBSCRIPTION
                 fi
 
                 az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "ARM_SUBSCRIPTION_ID.value" | tr -d \")
-                if [ ! -z ${az_var} ]; then
-                  export ARM_SUBSCRIPTION_ID=${az_var}  ; echo 'Target subscription' $ARM_SUBSCRIPTION_ID
-                else
+                if [ -z ${az_var} ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
                   exit 2
+                else
+                  export ARM_SUBSCRIPTION_ID=${az_var}  ; echo 'Target subscription' $ARM_SUBSCRIPTION_ID
+                  
                 fi
 
                 az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Workload_Key_Vault.value" | tr -d \")
@@ -260,7 +274,7 @@ stages:
                 rm -f terraform_$(tf_version)_linux_amd64.zip
 
               echo -e "$green--- az login ---$reset"
-                az login --service-principal --username $(ARM_CLIENT_ID) --password $ARM_CLIENT_SECRET --tenant $(ARM_TENANT_ID) --output none
+                az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
                 return_code=$?
                 if [ 0 != $return_code ]; then
                   echo -e "$boldred--- Login failed ---$reset"
@@ -302,8 +316,8 @@ stages:
               echo -e "$green--- Deploy the workload zone ---$reset"
                 cd $HOME/LANDSCAPE/$(workload_zone_folder)
                 $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)       \
-                  --deployer_environment $(deployer_environment) --subscription ${ARM_SUBSCRIPTION_ID}                                 \
-                  --spn_id $(ARM_CLIENT_ID) --spn_secret $ARM_CLIENT_SECRET --tenant_id $(ARM_TENANT_ID)                               \
+                  --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
+                  --spn_id $ARM_CLIENT_ID --spn_secret $ARM_CLIENT_SECRET --tenant_id $ARM_TENANT_ID                                   \
                   --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${key_vault}" --storageaccountname "${REMOTE_STATE_SA}" \
                   --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
                 return_code=$?
@@ -374,42 +388,42 @@ stages:
               echo -e "$green--- Adding variables to the variable group " $(variable_group) "---$reset"
                 az logout
                 if [ -n $VARIABLE_GROUP_ID ]; then
-                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "${NETWORK}"Workload_Key_Vault.value)  | tr -d \"
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "${NETWORK}"Workload_Key_Vault.value | tr -d \")
                   if [ -z ${az_var} ]; then
                     az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name "${NETWORK}"Workload_Key_Vault --value $workload_key_vault --output none --only-show-errors
                   else
                     az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name "${NETWORK}"Workload_Key_Vault --value $workload_key_vault --output none --only-show-errors
                   fi
 
-                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "${NETWORK}"Workload_Zone_State_FileName.value)  | tr -d \"
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "${NETWORK}"Workload_Zone_State_FileName.value | tr -d \")
                   if [ -z ${az_var} ]; then
                     az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name "${NETWORK}"Workload_Zone_State_FileName --value $landscape_tfstate_key --output none --only-show-errors
                   else
                     az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name "${NETWORK}"Workload_Zone_State_FileName --value $landscape_tfstate_key --output none --only-show-errors
                   fi
 
-                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value" | tr -d \")
                   if [ -z ${az_var} ]; then
                     az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value $REMOTE_STATE_SA --output none --only-show-errors
                   else
                     az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value $REMOTE_STATE_SA --output none --only-show-errors
                   fi
 
-                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Subscription.value")
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Subscription.value" | tr -d \")
                   if [ -z ${az_var} ]; then
                     az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value "${STATE_SUBSCRIPTION}" --output none --only-show-errors
                   else
                     az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value "${STATE_SUBSCRIPTION}" --output none --only-show-errors
                   fi
 
-                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value")
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value" | tr -d \")
                   if [ -z ${az_var} ]; then
                     az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value $deployer_tfstate_key --output none --only-show-errors
                   else
                     az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value $deployer_tfstate_key --output none --only-show-errors
                   fi
 
-                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value")
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value" | tr -d \")
                   if [ -z ${az_var} ]; then
                     az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${key_vault} --output none --only-show-errors
                   else
@@ -432,6 +446,7 @@ stages:
             displayName:               Deploy SAP Workload Zone
             env:
               SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
+              ARM_SUBSCRIPTION_ID:     $(ARM_SUBSCRIPTION_ID)
               ARM_CLIENT_ID:           $(ARM_CLIENT_ID)
               ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
               ARM_TENANT_ID:           $(ARM_TENANT_ID)
diff --git a/deploy/pipelines/10-remover-terraform.yaml b/deploy/pipelines/10-remover-terraform.yaml
--- a/deploy/pipelines/10-remover-terraform.yaml
+++ b/deploy/pipelines/10-remover-terraform.yaml
@@ -58,7 +58,7 @@ parameters:
 trigger:                               none
 
 pool:
-  name:                                $(Agent)
+  name:                                $[coalesce(variables['POOL'], variables['Agent'])]
 
 variables:
   - group:                             "SDAF-General"
@@ -171,14 +171,22 @@ stages:
                 az devops configure -d project=$(System.TeamProject)
 
                 export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]"); echo VARIABLE_GROUP_ID $VARIABLE_GROUP_ID
+                if [ -z ${VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
+                    exit 2
+                fi
 
                 export PARENT_VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(parent_variable_group)'].id | [0]"); echo PARENT_VARIABLE_GROUP_ID $PARENT_VARIABLE_GROUP_ID
+                if [ -z ${PARENT_VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(parent_variable_group) could not be found."
+                    exit 2
+                fi
 
               echo -e "$green--- Set variables ---$reset"
                 echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
 
-                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query $NETWORK"Workload_Key_Vault.value")
-                if [ -z "${az_var}" ]; then
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query $NETWORK"Workload_Key_Vault.value" | tr -d \")
+                if [ -z ${az_var} ]; then
                   export workload_key_vault=$(cat "${workload_environment_file_name}"  | grep workloadkeyvault      | awk -F'=' '{print $2}' | xargs) ; echo 'Workload Key Vault' ${workload_key_vault}
                 else
                   export workload_key_vault="${az_var}" ; echo 'Workload Key Vault' ${workload_key_vault}
@@ -357,7 +365,7 @@ stages:
                   echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
                   exit 2
                 fi
-                if -z $(ARM_CLIENT_ID) ]; then
+                if [ -z $(ARM_CLIENT_ID) ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
                   exit 2
                 fi
@@ -384,9 +392,19 @@ stages:
                 az devops configure -d organization=$(System.CollectionUri)
                 az devops configure -d project=$(System.TeamProject)
 
-                export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]"); echo VARIABLE_GROUP_ID $VARIABLE_GROUP_ID
+                export PARENT_VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(parent_variable_group)'].id | [0]")
+                echo '$(parent_variable_group) id: ' $PARENT_VARIABLE_GROUP_ID
+                if [ -z ${PARENT_VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(parent_variable_group) could not be found."
+                    exit 2
+                fi
 
-                export PARENT_VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(parent_variable_group)'].id | [0]"); echo PARENT_VARIABLE_GROUP_ID $PARENT_VARIABLE_GROUP_ID
+                export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
+                echo '$(variable_group) id: ' $VARIABLE_GROUP_ID
+                if [ -z ${VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
+                    exit 2
+                fi
 
               echo -e "$green--- Set WORKSPACES folder as new home ---$reset"
 
@@ -402,7 +420,7 @@ stages:
                 echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
 
                 az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query $NETWORK"Workload_Key_Vault.value")
-                if [ -z "${az_var}" ]; then
+                if [ -z ${az_var} ]; then
                   export workload_key_vault=$(cat "${workload_environment_file_name}"  | grep workloadkeyvault      | awk -F'=' '{print $2}' | xargs) ; echo 'Workload Key Vault' ${workload_key_vault}
                 else
                   export workload_key_vault="${az_var}" ; echo 'Workload Key Vault' ${workload_key_vault}
@@ -609,6 +627,11 @@ stages:
                 az devops configure -d project=$(System.TeamProject)
 
                 export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(parent_variable_group)'].id | [0]")
+                echo '$(variable_group) id: ' $VARIABLE_GROUP_ID
+                if [ -z ${VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(parent_variable_group) could not be found."
+                    exit 2
+                fi
 
               echo -e "$green--- Convert config files to UX format ---$reset"
                 sudo apt-get -qq install dos2unix
