Pipeline updates
Additional debugging, persisting variables to variable groups

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -24,9 +24,9 @@ parameters:
     default:                           MGMT
   
   - name:                              use_webapp
-    displayName:                       "Deploy the web app infrastructure"
+    displayName:                       "Deploy the configuration web application"
     type:                              boolean
-    default:                           false
+    default:                           true
 
 trigger:                               none
 
@@ -36,7 +36,7 @@ pool:
 variables:
   - group:                             "SDAF-General"
   - group:                             SDAF-${{ parameters.environment }}
-  - name:                              variablegroup
+  - name:                              variable_group
     value:                             SDAF-${{ parameters.environment }}
   - name:                              use_webapp
     value:                             ${{ lower(parameters.use_webapp) }}
@@ -64,7 +64,7 @@ stages:
         steps:
           - checkout:                  self
             persistCredentials:        true
-          - script: |
+          - bash: |
               #!/bin/bash
               echo "##vso[build.updatebuildnumber]Deploying the control plane defined in $(deployerfolder) $(libraryfolder)"
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
@@ -116,28 +116,19 @@ stages:
                   echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
                   exit 2
                 fi
-                if [ $(use_webapp) = "true" ]; then
-                  if [ ! -n $(TF_VAR_app_registration_app_id) ]; then
-                    echo "##vso[task.logissue type=error]Variable TF_VAR_app_registration_app_id was not defined."
+                if [ $(use_webapp) ]; then
+                  echo "Use WebApp is selected"
+                  if [ -z $(APP_REGISTRATION_APP_ID) ]; then
+                    echo "##vso[task.logissue type=error]Variable APP_REGISTRATION_APP_ID was not defined."
                     exit 2
+                  
                   fi
-                  if [ ! -n $(TF_VAR_webapp_client_secret) ]; then
-                    echo "##vso[task.logissue type=error]Variable TF_VAR_webapp_client_secret was not defined."
+                  if [ -z $(WEB_APP_CLIENT_SECRET) ]; then
+                    echo "##vso[task.logissue type=error]Variable WEB_APP_CLIENT_SECRET was not defined."
                     exit 2
                   fi
                 fi
 
-              echo -e "$green--- az login ---$reset"
-                az login --service-principal --username $(ARM_CLIENT_ID) --password $ARM_CLIENT_SECRET --tenant $(ARM_TENANT_ID)
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo -e "$boldred--- Login failed ---$reset"
-                  echo "##vso[task.logissue type=error]az login failed."
-                  exit $return_code
-                fi
-
-                az account set --subscription $(ARM_SUBSCRIPTION_ID)
-                az extension add --name storage-blob-preview > /dev/null
               echo -e "$green--- Pull the latest content from DevOps ---$reset"
                 git config --global user.email "$(Build.RequestedForEmail)"
                 git config --global user.name "$(Build.RequestedFor)"
@@ -145,11 +136,24 @@ stages:
                 git pull
 
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                az extension add --name azure-devops
+                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
                 az devops configure -d organization=$(System.CollectionUri)
                 az devops configure -d project=$(System.TeamProject)
-                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
-                export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variablegroup)'].id | [0]")
+                if [ -n $(PAT) ]; then
+                  export AZURE_DEVOPS_EXT_PAT=$(PAT)
+                else
+                  export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
+                fi
+                export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]"); echo VARIABLE_GROUP_ID ${VARIABLE_GROUP_ID}
+
+                if [ -n $(POOL) ]; then
+                  export POOL_NAME=$(az pipelines pool list --query "[?name=='$(POOL)'].name | [0]") ; echo POOL ${POOL_NAME}
+                  if [ -z ${POOL_NAME} ]; then
+                    echo "##vso[task.logissue type=error]Agent Pool $(POOL) does not exist."
+                    exit 2
+                  fi
+
+                fi
 
               echo -e "$green--- Convert config files to UX format ---$reset"
                 sudo apt-get -qq install dos2unix
@@ -159,27 +163,52 @@ stages:
               echo -e "$green--- Exporting webapp variables ---$reset"
                 export IS_PIPELINE_DEPLOYMENT=true
                 export TF_VAR_use_webapp=$(use_webapp)
-                if [ $(use_webapp) = "true" ]; then
-                  export TF_VAR_app_registration_app_id=$(TF_VAR_app_registration_app_id)
-                  export TF_VAR_webapp_client_secret=$(TF_VAR_webapp_client_secret)
+                if [ $(use_webapp) == "true" ]; then
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "APP_REGISTRATION_APP_ID")
+                  if [ ! -z "${az_var}" ]; then
+                    export TF_VAR_app_registration_app_id=$(APP_REGISTRATION_APP_ID); echo 'App ID' "${TF_VAR_app_registration_app_id}"
+                  fi
+                  
+                  az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "WEB_APP_CLIENT_SECRET")
+                  if [ ! -z "${az_var}" ]; then
+                    export TF_VAR_webapp_client_secret=$(WEB_APP_CLIENT_SECRET); echo 'Secret' "${TF_VAR_webapp_client_secret}"
+                  fi
                 fi
               
               deployer_environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}$LOCATION
 
+              export key_vault=""
+
               if [ -f ${deployer_environment_file_name} ]; then
-                export keyvault=$(cat ${deployer_environment_file_name}  | grep keyvault | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${keyvault}
-                length=$(expr length "$keyvault")
+                export key_vault=$(cat ${deployer_environment_file_name}  | grep key_vault | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
+                length=$(expr length "$key_vault")
 
                 ip_added=0
 
-                if [[ "Azure Pipelines" == "$(Agent)" ]]; then
+                agent_name=$(echo $(Agent) | tr '[:upper:]' '[:lower:]')
+
+                if [[ "azure pipelines" == "${agent_name}" ]]; then
                   if [ 0 != $length ]; then
                     this_ip=$(curl -s ipinfo.io/ip) >/dev/null 2>&1
-                    az keyvault network-rule add --name ${keyvault} --ip-address ${this_ip} --no-wait
-                    ip_added=1
+                    if [ -n ${key_vault} ]; then
+                      az keyvault network-rule add --name ${key_vault} --ip-address ${this_ip} --only-show-errors --output none
+                      ip_added=1
+                    fi
                   fi
                 fi
               fi
+
+              echo -e "$green--- az login ---$reset"
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $ARM_CLIENT_SECRET --tenant $(ARM_TENANT_ID) --output none
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo -e "$boldred--- Login failed ---$reset"
+                  echo "##vso[task.logissue type=error]az login failed."
+                  exit $return_code
+                fi
+
+                az account set --subscription $(ARM_SUBSCRIPTION_ID)
+                az extension add --name storage-blob-preview > /dev/null
 
               echo -e "$green--- Deploy the Control Plane ---$reset"
 
@@ -191,15 +220,23 @@ stages:
                   export TF_VAR_agent_pool=$(POOL); echo 'Deployer Agent Pool' ${TF_VAR_agent_pool}
                 fi
 
-                $DEPLOYMENT_REPO_PATH/deploy/scripts/prepare_region.sh                   \
+                storage_account_parameter=""
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
+                if [ -n "${az_var}" ]; then
+                  storage_account_parameter='--storageaccountname $(Terraform_Remote_Storage_Account_Name)'
+                fi
+
+                $DEPLOYMENT_REPO_PATH/deploy/scripts/deploy_controlplane.sh                   \
                   --deployer_parameter_file DEPLOYER/$(deployerfolder)/$(deployerconfig) \
                   --library_parameter_file LIBRARY/$(libraryfolder)/$(libraryconfig)     \
                   --subscription $(ARM_SUBSCRIPTION_ID)  --spn_id $(ARM_CLIENT_ID)       \
-                  --spn_secret $ARM_CLIENT_SECRET --tenant_id $(ARM_TENANT_ID)         \
-                  --auto-approve --ado
+                  --spn_secret $ARM_CLIENT_SECRET --tenant_id $(ARM_TENANT_ID)           \
+                  --auto-approve --ado                                                   \
+                  ${storage_account_parameter}
                 return_code=$?
+
                 if [ 0 != $return_code ]; then
-                  echo "##vso[task.logissue type=error]Return code from prepare_region $return_code."
+                  echo "##vso[task.logissue type=error]Return code from deploy_controlplane $return_code."
                   if [ -f .sap_deployment_automation/${ENVIRONMENT}${LOCATION}.err ]; then
                     error_message=$(cat .sap_deployment_automation/${ENVIRONMENT}${LOCATION}.err)
                     echo "##vso[task.logissue type=error]Error message: $error_message."
@@ -208,9 +245,13 @@ stages:
 
                 if [[ 1 -eq $ip_added ]]; then
 
-                  if [[ "Azure Pipelines" == "$(Agent)" ]]; then
+                  agent_name=$(echo $(Agent) | tr '[:upper:]' '[:lower:]')
+
+                  if [[ "azure pipelines" == "${agent_name}" ]]; then
                     this_ip=$(curl -s ipinfo.io/ip) >/dev/null 2>&1
-                    az keyvault network-rule remove --name ${keyvault} --ip-address ${this_ip} --no-wait
+                    if [ -n ${key_vault} ]; then
+                      az keyvault network-rule remove --name ${key_vault} --ip-address ${this_ip} --no-wait --only-show-errors --output none
+                    fi
                   fi
                 fi
 
@@ -220,10 +261,46 @@ stages:
                 added=0
                 cd $HOME
                 git pull
+                deployer_environment_file_name=.sap_deployment_automation/${ENVIRONMENT}${LOCATION}
+                az logout --output none
 
-                if [ -f .sap_deployment_automation/${ENVIRONMENT}${LOCATION} ]; then
+                if [ -f ${deployer_environment_file_name} ]; then
+                  
+                  export deployer_tfstate_key=$(cat ${deployer_environment_file_name}  | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
+                  export            key_vault=$(cat ${deployer_environment_file_name}  | grep keyvault=            | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
+                  export      REMOTE_STATE_SA=$(cat ${deployer_environment_file_name}  | grep REMOTE_STATE_SA      | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform state file storage account' $REMOTE_STATE_SA
+
                   git add    .sap_deployment_automation/${ENVIRONMENT}${LOCATION}
                   added=1
+                fi
+
+              echo -e "$green--- Adding variables to the variable group:" $(variable_group) "---$reset"
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Account_Name.value")
+                if [ -z "${az_var}" ]; then
+                  az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value $REMOTE_STATE_SA --output none --only-show-errors
+                else
+                  az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Account_Name --value $REMOTE_STATE_SA --output none --only-show-errors
+                fi
+
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Terraform_Remote_Storage_Subscription.value")
+                if [ -z "${az_var}" ]; then
+                  az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value $(ARM_SUBSCRIPTION_ID) --output none --only-show-errors
+                else
+                  az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Terraform_Remote_Storage_Subscription --value $(ARM_SUBSCRIPTION_ID) --output none --only-show-errors
+                fi
+
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_State_FileName.value")
+                if [ -z "${az_var}" ]; then
+                  az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value $deployer_tfstate_key --output none --only-show-errors
+                else
+                  az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_State_FileName --value $deployer_tfstate_key --output none --only-show-errors
+                fi
+
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "Deployer_Key_Vault.value")
+                if [ -z "${az_var}" ]; then
+                  az pipelines variable-group variable create --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${key_vault} --output none --only-show-errors
+                else
+                  az pipelines variable-group variable update --group-id ${VARIABLE_GROUP_ID} --name Deployer_Key_Vault --value ${key_vault} --output none --only-show-errors
                 fi
 
                 if [ -f .sap_deployment_automation/${ENVIRONMENT}${LOCATION}.md ]; then
@@ -261,7 +338,6 @@ stages:
                     added=1
                 fi
 
-
                 if [ 1 == $added ]; then
                   git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]" 
                   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push 
@@ -280,6 +356,7 @@ stages:
               ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
               ARM_TENANT_ID:           $(ARM_TENANT_ID)
               TF_VAR_agent_ado_url:    $(System.CollectionUri)
+              AZURE_DEVOPS_EXT_PAT:    $(PAT)
             failOnStderr:              false
 
 ...
diff --git a/deploy/pipelines/04-sap-software-download.yaml b/deploy/pipelines/04-sap-software-download.yaml
--- a/deploy/pipelines/04-sap-software-download.yaml
+++ b/deploy/pipelines/04-sap-software-download.yaml
@@ -16,10 +16,10 @@ parameters:
     default:                           
     values:
       - S4HANA_2021_ISS_v0001ms
-      - S42020SPS03_v0003ms
+      - S42020SPS04_v0001ms
       - S41909SPS03_v0011ms
       - HCMT_v0001ms
-      - BW4HANA2021SPS01_v0001ms
+      - BW4HANA2021SPS01_v0003ms
       - HANA_2_00_063_v0001ms
       - HANA_2_00_061_v0001ms
       - HANA_2_00_059_v0003ms
@@ -28,6 +28,7 @@ parameters:
       - NW752SPS09_v0001ms
       - ORACLE_19_00_v0002ms
       - ORACLE_19_00_ORA_MSID_v0002ms
+      - ERP6_EHP8_WIN_MSS2019_v0001ms
 
   - name:                              environment
     displayName:                       Control Plane Environment
@@ -46,7 +47,7 @@ parameters:
 trigger:                               none
 
 pool:
-  name:                                $(Agent)
+  name:                                $[coalesce(variables['POOL'], variables['Agent'])]
 
 variables:
   - group:                             "SDAF-General"
@@ -97,6 +98,11 @@ stages:
                   exit 2
                 fi
 
+                if [ "Azure Pipelines" == $(Agent) ]; then
+                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-$(environment_code) variable group"
+                  exit 2
+                fi
+                
                 if [ ! -n $(ARM_CLIENT_ID) ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
                   exit 2
@@ -112,7 +118,7 @@ stages:
                   exit 2
                 fi
 
-                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID) --output none
                 return_code=$?
                 if [ 0 != $return_code ]; then
                   echo -e "$boldred--- Login failed ---$reset"
@@ -232,6 +238,5 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-              ANSIBLE_CALLBACK_WHITELIST: profile_tasks
 
 ...
diff --git a/deploy/pipelines/05-DB-and-SAP-installation.yaml b/deploy/pipelines/05-DB-and-SAP-installation.yaml
--- a/deploy/pipelines/05-DB-and-SAP-installation.yaml
+++ b/deploy/pipelines/05-DB-and-SAP-installation.yaml
@@ -13,19 +13,19 @@ parameters:
   - name:                              sap_system_configuration_name
     displayName:                       "SAP System configuration name, use the following syntax: ENV-LOCA-VNET-SID"
     type:                              string
-    default:                           DEV-WEEU-SAP01-X00
+    default:                           PRD-UKSO-SAP07-RHB
 
   - name:                              environment
     displayName:                       Workload Environment (DEV, QUA, PRD, ...)
     type:                              string
-    default:                           DEV
+    default:                           PRD
 
   - name:                              bom_base_name
     displayName:                       Bill of Materials name
     type:                              string
     values:
       - S4HANA_2021_ISS_v0001ms
-      - S42020SPS03_v0003ms
+      - S42020SPS04_v0001ms
       - S41909SPS03_v0011ms
       - HANA_2_00_063_v0001ms
       - HANA_2_00_061_v0001ms
@@ -95,9 +95,11 @@ variables:
     value:                             ${{ parameters.sap_system_configuration_name }}
   - name:                              bom
     value:                             ${{ parameters.bom_base_name }}
+  - name:                              agent_name
+    value:                             $[coalesce(variables['POOL'], variables['Agent'])]
 
 pool:
-  name:                                $(Agent)
+  name:                                $[coalesce(variables['POOL'], variables['Agent'])]
 
 stages:
   - stage:                             Preparation_for_Ansible
@@ -126,10 +128,15 @@ stages:
                 VIRTUAL_NET=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo Virtual network logical name $VIRTUAL_NET
                         SID=$(echo $(sap_system_folder) | awk -F'-' '{print $4}' | xargs) ; echo SID $SID
 
-                        ls $HOME/SYSTEM/$(sap_system_folder)
-
                 environment_file_name=$HOME/.sap_deployment_automation/$ENVIRONMENT$LOCATION ; echo configuration_file $environment_file_name
                           params_file=$HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml ;  echo sap_parameters_file $params_file
+
+                agent_name=$(echo $(agent_name) | tr '[:upper:]' '[:lower:]')
+
+                if [[ "azure pipelines" == "${agent_name}" ]]; then
+                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-${ENVIRONMENT} variable group"
+                  exit 2
+                fi
 
                 if [ ! -f $environment_file_name ]; then
                   echo -e "$boldred--- $environment_file_name was not found ---$reset"
@@ -144,9 +151,7 @@ stages:
                 else
                   dos2unix -q $HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml
                 fi
-                echo "3"
                 
-
                 if [ ! -n ${SID} ]; then
                   echo "##vso[task.logissue type=error]SID was not found in $(sap_system_folder)."
                   exit 2
@@ -189,7 +194,7 @@ stages:
                   exit 2
                 fi
 
-                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID) --output none
                 return_code=$?
                 if [ 0 != $return_code ]; then
                   echo -e "$boldred--- Login failed ---$reset"
@@ -208,8 +213,12 @@ stages:
               echo -e "$green--- Get sshkey to connect to SAP VMs ---$reset"
                 mkdir -p artifacts
 
-                export kv_name=$(cat $environment_file_name  | grep workloadkeyvault | awk -F'=' '{print $2}' | xargs) ; echo SAP_Keyvault $kv_name
-                az keyvault secret show --name ${ENVIRONMENT}-${LOCATION}-${VIRTUAL_NET}-sid-sshkey --vault-name $kv_name --query value -o tsv > artifacts/$(sap_system_folder)_sshkey
+                if [ -n $(Workload_Key_Vault) ]; then
+                  export workload_key_vault=$(Workload_Key_Vault) ; echo 'Workload Key Vault' ${workload_key_vault}
+                else
+                  export workload_key_vault=$(cat "${environment_file_name}"  | grep workload_key_vault      | awk -F'=' '{print $2}' | xargs) ; echo 'Workload Key Vault' ${workload_key_vault}
+                fi
+                az keyvault secret show --name ${ENVIRONMENT}-${LOCATION}-${VIRTUAL_NET}-sid-sshkey --vault-name $workload_key_vault --query value -o tsv > artifacts/$(sap_system_folder)_sshkey
                 cp sap-parameters.yaml artifacts/.
                 cp ${SID}_hosts.yaml artifacts/.
 
@@ -282,9 +291,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
 
   - stage:                             Core_Operating_System_Configuration
@@ -331,9 +339,9 @@ stages:
 
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
-              ANSIBLE_CALLBACK_WHITELIST: profile_tasks
               ANSIBLE_HOST_KEY_CHECKING: false
               DEPLOYMENT_REPO_PATH:    $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
 
   - stage:                             SAP_Operating_System_Configuration
@@ -379,9 +387,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
 
   - stage:                             Software_Acquisition
@@ -429,9 +436,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
 
   - stage: Database_Installation
@@ -481,9 +487,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
           - script: |
               #!/bin/bash
@@ -553,9 +558,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
               continueOnError:           true
           - script: |
               #!/bin/bash
@@ -629,8 +633,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           true
           - script: |
               #!/bin/bash
@@ -701,8 +705,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
             name: HA
 
@@ -758,8 +762,8 @@ stages:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
 
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           true
           - script: |
               #!/bin/bash
@@ -835,8 +839,8 @@ stages:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
 
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           true
           - script: |
               #!/bin/bash
@@ -901,9 +905,8 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
-
-              ANSIBLE_CALLBACK_WHITELIST:    profile_tasks
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           true
           - script: |
               #!/bin/bash
