chore: Improve error handling and logging in deploy control plane pipeline

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -423,6 +423,18 @@ stages:
 
                           deployer_random_id=$(cat ${deployer_environment_file_name} | grep deployer_random_id= | awk -F'=' '{print $2}' | xargs)
 
+                          validation=$(echo $(DEPLOYER_RANDOM_ID_SEED))
+
+                          if [ '$(DEPLOYER_RANDOM_ID_SEED)' == $validation ]; then
+                              echo "##vso[task.logissue type=error]DEPLOYER_RANDOM_ID_SEED is not defined."
+                              exit 2
+                          fi
+
+                          if [ -z ${validation} ]; then
+                              echo "##vso[task.logissue type=error]DEPLOYER_RANDOM_ID_SEED is not defined."
+                              exit 2
+                          fi
+
                       echo -e "$green--- Information ---$reset"
                           echo "Environment:    ${ENVIRONMENT}"
                           echo "Location:       ${LOCATION}"
