do an az login if reset

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -109,6 +109,13 @@ stages:
                                 key_vault=$(cat ${deployer_environment_file_name} | grep keyvault= -m1 | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' ${key_vault}
                               fi
 
+                              az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
+                              return_code=$?
+                              if [ 0 != $return_code ]; then
+                                  echo -e "$boldred--- Login failed ---$reset"
+                                  echo "##vso[task.logissue type=error]az login failed."
+                                  exit $return_code
+                              fi
 
                               this_ip=$(curl -s ipinfo.io/ip) >/dev/null 2>&1
                               az keyvault network-rule add --name ${key_vault} --ip-address ${this_ip} --only-show-errors --output none
