logon as SPN

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -515,6 +515,13 @@ stages:
 
                       else
                           source /etc/profile.d/deploy_server.sh
+                          az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
+                          return_code=$?
+                          if [ 0 != $return_code ]; then
+                              echo -e "$boldred--- Login failed ---$reset"
+                              echo "##vso[task.logissue type=error]az login failed."
+                              exit $return_code
+                          fi
                       fi
 
                       echo -e "$green--- Configure parameters ---$reset"
