When running on deployer source the variables

diff --git a/deploy/pipelines/01-deploy-control-plane.yaml b/deploy/pipelines/01-deploy-control-plane.yaml
--- a/deploy/pipelines/01-deploy-control-plane.yaml
+++ b/deploy/pipelines/01-deploy-control-plane.yaml
@@ -502,6 +502,19 @@ stages:
                           rm -f terraform_$(tf_version)_linux_amd64.zip
 
                           az extension add --name storage-blob-preview >/dev/null
+                          echo -e "$green--- az login ---$reset"
+                          az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
+                          return_code=$?
+                          if [ 0 != $return_code ]; then
+                              echo -e "$boldred--- Login failed ---$reset"
+                              echo "##vso[task.logissue type=error]az login failed."
+                              exit $return_code
+                          fi
+
+                          az account set --subscription $ARM_SUBSCRIPTION_ID
+
+                      else
+                          source /etc/profile.d/deploy_server.sh
                       fi
 
                       echo -e "$green--- Configure parameters ---$reset"
@@ -531,17 +544,6 @@ stages:
                                   fi
                               fi
                           fi
-
-                      echo -e "$green--- az login ---$reset"
-                          az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
-                          return_code=$?
-                          if [ 0 != $return_code ]; then
-                              echo -e "$boldred--- Login failed ---$reset"
-                              echo "##vso[task.logissue type=error]az login failed."
-                              exit $return_code
-                          fi
-
-                          az account set --subscription $ARM_SUBSCRIPTION_ID
 
                           echo -e "$green--- Deploy the Control Plane ---$reset"
 
