misc fixes

diff --git a/deploy/pipelines/01-prepare-region.yaml b/deploy/pipelines/01-prepare-region.yaml
--- a/deploy/pipelines/01-prepare-region.yaml
+++ b/deploy/pipelines/01-prepare-region.yaml
@@ -1,18 +1,17 @@
 # This pipeline prepares the region with a deployer and a SAP library
 
 parameters:
-- name: deployer
-  displayName: ENV-LOCA-VNET-INFRASTRUCTURE
-  type: string
-  default: MGMT-WEEU-DEP00-INFRASTRUCTURE
+  - name: deployer
+    displayName: ENV-LOCA-VNET-INFRASTRUCTURE
+    type: string
+    default: MGMT-WEEU-DEP00-INFRASTRUCTURE
 
-- name: library
-  displayName: ENV-LOCA-SAP_LIBRARY
-  type: string
-  default: MGMT-WEEU-SAP_LIBRARY
+  - name: library
+    displayName: ENV-LOCA-SAP_LIBRARY
+    type: string
+    default: MGMT-WEEU-SAP_LIBRARY
 
-trigger:
-  none
+trigger: none
 
 pool:
   vmImage: ubuntu-latest
@@ -25,134 +24,134 @@ variables:
   log: logfile_$(Build.BuildId)
   tf_url: https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip
 
-name: Control Plane Deployment $(deployerfolder)_$(libraryfolder) $(Date:yyyyMMdd) $(SourceBranchName)_$(Rev:.r)
+name: Control Plane Deployment $(deployerfolder)_$(libraryfolder) $(Date:yyyyMMdd) $(SourceBranchName)
 
 stages:
-- stage: Prepare_region
-  displayName: Deploy the control plane
-  jobs:
-  - job: Prepare_region
+  - stage: Prepare_region
     displayName: Deploy the control plane
-    steps:
-    - script: |
-        #!/bin/bash
-        green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+    jobs:
+      - job: Prepare_region
+        displayName: Deploy the control plane
+        steps:
+          - script: |
+              #!/bin/bash
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
 
-        echo -e "$green--- Install Terraform ---$reset"
-          wget -q $(tf_url)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-            exit 2
-          fi
-          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+              echo -e "$green--- Install Terraform ---$reset"
+                wget -q $(tf_url)
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                  exit 2
+                fi
+                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
 
-        echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-          export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-          export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
-          cd $HOME; mkdir -p .sap_deployment_automation
-          echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
+                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
+                cd $HOME; mkdir -p .sap_deployment_automation
+                echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
 
-        echo -e "$green--- Validations ---$reset"
-          if [ ! -f DEPLOYER/$(deployerfolder)/$(deployerconfig) ]; then
-            echo -e "$boldred--- File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found ---$reset"
-            echo "##vso[task.logissue type=error]File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found."
-            exit 2
-          fi
-          if [ ! -f LIBRARY/$(libraryfolder)/$(libraryconfig) ]; then
-            echo -e "$boldred--- File LIBRARY/$(libraryfolder)/$(libraryconfig)  was not found ---$reset"
-            echo "##vso[task.logissue type=error]File LIBRARY/$(libraryfolder)/$(libraryconfig) was not found."
-            exit 2
-          fi
-          if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-            exit 2
-          fi
-          if [ ! -n $(ARM_CLIENT_ID) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-            exit 2
-          fi
-          if [ ! -n $(ARM_CLIENT_SECRET) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-            exit 2
-          fi
-          if [ ! -n $(ARM_TENANT_ID) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-            exit 2
-          fi
+              echo -e "$green--- Validations ---$reset"
+                if [ ! -f DEPLOYER/$(deployerfolder)/$(deployerconfig) ]; then
+                  echo -e "$boldred--- File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found ---$reset"
+                  echo "##vso[task.logissue type=error]File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found."
+                  exit 2
+                fi
+                if [ ! -f LIBRARY/$(libraryfolder)/$(libraryconfig) ]; then
+                  echo -e "$boldred--- File LIBRARY/$(libraryfolder)/$(libraryconfig)  was not found ---$reset"
+                  echo "##vso[task.logissue type=error]File LIBRARY/$(libraryfolder)/$(libraryconfig) was not found."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_CLIENT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_CLIENT_SECRET) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_TENANT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                  exit 2
+                fi
 
-        echo -e "$green--- az login ---$reset"
-          export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
-          export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
-          export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
-          export ARM_TENANT_ID=$(ARM_TENANT_ID)
-          az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo -e "$boldred--- Login failed ---$reset"
-            echo "##vso[task.logissue type=error]az login failed."
-            exit $return_code
-          fi
+              echo -e "$green--- az login ---$reset"
+                export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
+                export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
+                export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
+                export ARM_TENANT_ID=$(ARM_TENANT_ID)
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo -e "$boldred--- Login failed ---$reset"
+                  echo "##vso[task.logissue type=error]az login failed."
+                  exit $return_code
+                fi
 
-          az account set --subscription $(ARM_SUBSCRIPTION_ID)
-          az extension add --name storage-blob-preview > /dev/null
+                az account set --subscription $(ARM_SUBSCRIPTION_ID)
+                az extension add --name storage-blob-preview > /dev/null
 
-        echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
-          organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
-          git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
+              echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
+                organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
+                git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
 
-        echo -e "$green--- Convert config files to UX format ---$reset"
-          sudo apt-get -qq install dos2unix
-          dos2unix -q DEPLOYER/$(deployerfolder)/$(deployerconfig)
-          dos2unix -q LIBRARY/$(libraryfolder)/$(libraryconfig) 
+              echo -e "$green--- Convert config files to UX format ---$reset"
+                sudo apt-get -qq install dos2unix
+                dos2unix -q DEPLOYER/$(deployerfolder)/$(deployerconfig)
+                dos2unix -q LIBRARY/$(libraryfolder)/$(libraryconfig)
 
-        echo -e "$green--- Running the prepare region script that deploys the subscription hub with the Deployer VM and SAP Library ---$reset"
-          $DEPLOYMENT_REPO_PATH/deploy/scripts/prepare_region.sh --deployer_parameter_file DEPLOYER/$(deployerfolder)/$(deployerconfig) --library_parameter_file LIBRARY/$(libraryfolder)/$(libraryconfig)  --subscription $(ARM_SUBSCRIPTION_ID)  --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID)  --auto-approve
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo "##vso[task.logissue type=error]Return code from prepare_region $return_code."
-          fi
+              echo -e "$green--- Deploys the Control Plane ---$reset"
+                $DEPLOYMENT_REPO_PATH/deploy/scripts/prepare_region.sh --deployer_parameter_file DEPLOYER/$(deployerfolder)/$(deployerconfig) --library_parameter_file LIBRARY/$(libraryfolder)/$(libraryconfig)  --subscription $(ARM_SUBSCRIPTION_ID)  --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID)  --auto-approve
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo "##vso[task.logissue type=error]Return code from prepare_region $return_code."
+                fi
 
-        echo -e "$green--- Adding deployment automation configuration to devops repository ---$reset"
-          cd $(Build.Repository.LocalPath)
-          git config --global user.email "$(Build.RequestedForEmail)"
-          git config --global user.name  "$(Build.RequestedFor)"
-          git pull origin $(Branch)                                                                             &>> /tmp/$(log)
-          export ENV=$(echo $(deployerfolder)  | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENV
-          export LOCA=$(echo $(deployerfolder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCA
-          added=0
-          if [ -f $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA} ]; then
-            git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}                &>  /tmp/$(log)
-            added=1
-          fi
-          if [ -f $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
-            git add $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}.md                &>  /tmp/$(log)
-            added=1
-          fi
-          if [ -f $(Deployment_Configuration_Path)/DEPLOYER/$(deployerfolder)/.terraform/terraform.tfstate ]; then
-            git add -f $(Deployment_Configuration_Path)/DEPLOYER/$(deployerfolder)/.terraform/terraform.tfstate &>  /tmp/$(log)
-            added=1
-          fi
-          if [ -f $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/.terraform/terraform.tfstate ]; then
-            git add -f $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/.terraform/terraform.tfstate   &>  /tmp/$(log)
-            added=1
-          fi
-          if [ -f $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/backend-config.tfvars ]; then
-            git add $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/backend-config.tfvars          &>  /tmp/$(log)
-            added=1
-          fi
-          if [ 1 == $added ]; then
-            git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"                &>> /tmp/$(log)
-            git push origin HEAD:$(Branch)                                                                        &>> /tmp/$(log)
-          fi
-          cat /tmp/$(log)
-          git config --unset-all http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader
-          if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
-            echo "##vso[task.uploadsummary]$HOME/.sap_deployment_automation/${ENV}${LOCA}.md"
-          fi
-          
-          exit $return_code
-      displayName: Prepare region
-      env:
-          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-      failOnStderr: false
+              echo -e "$green--- Adding deployment automation configuration to devops repository ---$reset"
+                cd $(Build.Repository.LocalPath)
+                git config --global user.email "$(Build.RequestedForEmail)"
+                git config --global user.name  "$(Build.RequestedFor)"
+                git pull origin $(Branch)                                                                            &>> /tmp/$(log)
+                export ENV=$(echo $(deployerfolder)  | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENV
+                export LOCA=$(echo $(deployerfolder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCA
+                added=0
+                if [ -f $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA} ]; then
+                  git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}                &>  /tmp/$(log)
+                  added=1
+                fi
+                if [ -f $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
+                  git add $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}.md                &>  /tmp/$(log)
+                  added=1
+                fi
+                if [ -f $(Deployment_Configuration_Path)/DEPLOYER/$(deployerfolder)/.terraform/terraform.tfstate ]; then
+                  git add -f $(Deployment_Configuration_Path)/DEPLOYER/$(deployerfolder)/.terraform/terraform.tfstate &>  /tmp/$(log)
+                  added=1
+                fi
+                if [ -f $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/.terraform/terraform.tfstate ]; then
+                  git add -f $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/.terraform/terraform.tfstate   &>  /tmp/$(log)
+                  added=1
+                fi
+                if [ -f $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/backend-config.tfvars ]; then
+                  git add $(Deployment_Configuration_Path)/LIBRARY/$(libraryfolder)/backend-config.tfvars          &>  /tmp/$(log)
+                  added=1
+                fi
+                if [ 1 == $added ]; then
+                  git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"                &>> /tmp/$(log)
+                  git push origin HEAD:$(Branch)                                                                        &>> /tmp/$(log)
+                fi
+                cat /tmp/$(log)
+                git config --unset-all http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader
+                if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
+                  echo "##vso[task.uploadsummary]$HOME/.sap_deployment_automation/${ENV}${LOCA}.md"
+                fi
+
+                exit $return_code
+            displayName: Prepare region
+            env:
+              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+            failOnStderr: false
diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -1,18 +1,17 @@
 # This pipeline deploys the SAP workload zone (landscape) with required resources
 
 parameters:
-- name: workloadzone
-  displayName: ENV-LOCA-VNET-INFRASTRUCTURE
-  type: string
-  default: DEV-WEEU-SAP01-INFRASTRUCTURE
+  - name: workloadzone
+    displayName: ENV-LOCA-VNET-INFRASTRUCTURE
+    type: string
+    default: DEV-WEEU-SAP01-INFRASTRUCTURE
 
-- name: environment
-  displayName: Deployer Environment (MGMT, DEV, QUA, PRD, ...)
-  type: string
-  default: MGMT
+  - name: environment
+    displayName: Deployer Environment (MGMT, DEV, QA, PRD, ...)
+    type: string
+    default: MGMT
 
-trigger:
-  none
+trigger: none
 
 pool:
   vmImage: ubuntu-latest
@@ -24,122 +23,122 @@ variables:
   log: logfile_$(Build.BuildId)
   tf_url: https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip
 
-name: Deploy Workload zone $(zonefolder) [$(Date:yyyyMMdd) $(SourceBranchName)_$(Rev:.r)]
+name: Deploy Workload zone $(zonefolder) [$(Date:yyyyMMdd) $(SourceBranchName)]
 
 stages:
-- stage: Deploy_SAP_workloadzone
-  displayName: Deploy SAP workload zone
-  jobs:
-  - job: Deploy_SAP_workloadzone
+  - stage: Deploy_SAP_workloadzone
     displayName: Deploy SAP workload zone
-    steps:
-    - script: |
-        #!/bin/bash
-        green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
-        echo -e "$green--- Install Terraform ---$reset"
-          wget -q $(tf_url)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-            exit 2
-          fi
-          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
-        echo -e "$green--- Set WORKSPACES folder as new home ---$reset"
-          export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
-          cd $HOME; mkdir -p .sap_deployment_automation
-          echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
-          export ENV=$(echo $(zonefolder)  | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENV
-          export LOCA=$(echo $(zonefolder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCA
-          export deployer_tfstate_key=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
-          export keyvault=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep keyvault | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' $keyvault
-          export REMOTE_STATE_SA=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep REMOTE_STATE_SA | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform statefile storage account' $REMOTE_STATE_SA
-          export STATE_SUBSCRIPTION=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep STATE_SUBSCRIPTION | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform statefile subscription' $STATE_SUBSCRIPTION
-       
-        echo -e "$green--- Validations ---$reset"
-          if [ ! -f $HOME/.sap_deployment_automation/$(env)$LOCA ]; then
-            echo -e "$boldred--- $(env)$LOCA was not found ---$reset"
-            echo "##vso[task.logissue type=error]Control plane configuration file $(env)$LOC was not found."
-            exit 2
-          fi
-          if [ ! -f $HOME/LANDSCAPE/$(zonefolder)/$(zoneconfig) ]; then
-            echo -e "$boldred--- $(zoneconfig) was not found ---$reset"
-            echo "##vso[task.logissue type=error]File $(zoneconfig) was not found."
-            exit 2
-          fi
-          if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-            exit 2
-          fi
-          if [ ! -n $(ARM_CLIENT_ID) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-            exit 2
-          fi
-          if [ ! -n $(ARM_CLIENT_SECRET) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-            exit 2
-          fi
-          if [ ! -n $(ARM_TENANT_ID) ]; then
-            echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-            exit 2
-          fi
-        echo -e "$green--- Set DEPLOYMENT_REPO_PATH variable and ---$reset"
-        echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-          export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-        echo -e "$green--- az login ---$reset"
-          export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
-          export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
-          export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
-          export ARM_TENANT_ID=$(ARM_TENANT_ID)
-          az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo -e "$boldred--- Login failed ---$reset"
-            echo "##vso[task.logissue type=error]az login failed."
-            exit $return_code
-          fi
-          az account set --subscription $(ARM_SUBSCRIPTION_ID)
-        echo -e "$green--- --- Convert config file to UX format ---$reset"
-          sudo apt-get -qq install dos2unix
-          dos2unix -q LANDSCAPE/$(zonefolder)/$(zoneconfig)
-        echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
-          organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
-          git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
-        echo -e "$green--- Run the install workloadzone script that deploys the SAP networks ---$reset"
-          cd $HOME/LANDSCAPE/$(zonefolder)
-          $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(zoneconfig) --deployer_environment $(env) --subscription $(ARM_SUBSCRIPTION_ID) --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID) --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${keyvault}" --storageaccountname "${REMOTE_STATE_SA}" --subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
-          return_code=$?
-        echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
-          cd $(Build.Repository.LocalPath)
-          
-          git config --global user.email "$(Build.RequestedForEmail)"
-          git config --global user.name  "$(Build.RequestedFor)"
-          git pull origin $(Branch)                                                                             &>> /tmp/$(log)
-          added=0
-          if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA} ]; then
-            git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}                &>>  /tmp/$(log)
-            added=1
-          fi
-          if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
-            git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}.md             &>>  /tmp/$(log)
-            added=1
-          fi
-          if [ -f $(Deployment_Configuration_Path)/LANDSCAPE/$(zonefolder)/.terraform/terraform.tfstate ]; then
-            git add -f $(Deployment_Configuration_Path)/LANDSCAPE/$(zonefolder)/.terraform/terraform.tfstate    &>> /tmp/$(log)
-            added=1
-          fi
-          if [ 1 == $added ]; then
-            git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"              &>> /tmp/$(log)
-          
-            git push origin HEAD:$(Branch)                                                                      &>> /tmp/$(log)
-          fi
-        echo "output the log ---$reset"
-          cat /tmp/$(log)
-          if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
-            echo "##vso[task.uploadsummary]$HOME/.sap_deployment_automation/${ENV}${LOCA}.md"
-          fi
-          git config --unset-all http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader
-          exit $return_code
-      displayName: Deploy SAP Workload Zone
-      env:
-          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-      failOnStderr: true
+    jobs:
+      - job: Deploy_SAP_workloadzone
+        displayName: Deploy SAP workload zone
+        steps:
+          - script: |
+              #!/bin/bash
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+              echo -e "$green--- Install Terraform ---$reset"
+                wget -q $(tf_url)
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                  exit 2
+                fi
+                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+              echo -e "$green--- Set WORKSPACES folder as new home ---$reset"
+                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
+                cd $HOME; mkdir -p .sap_deployment_automation
+                echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+                export ENV=$(echo $(zonefolder)  | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENV
+                export LOCA=$(echo $(zonefolder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCA
+                export deployer_tfstate_key=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
+                export keyvault=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep keyvault | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' $keyvault
+                export REMOTE_STATE_SA=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep REMOTE_STATE_SA | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform statefile storage account' $REMOTE_STATE_SA
+                export STATE_SUBSCRIPTION=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep STATE_SUBSCRIPTION | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform statefile subscription' $STATE_SUBSCRIPTION
+
+              echo -e "$green--- Validations ---$reset"
+                if [ ! -f $HOME/.sap_deployment_automation/$(env)$LOCA ]; then
+                  echo -e "$boldred--- $(env)$LOCA was not found ---$reset"
+                  echo "##vso[task.logissue type=error]Control plane configuration file $(env)$LOC was not found."
+                  exit 2
+                fi
+                if [ ! -f $HOME/LANDSCAPE/$(zonefolder)/$(zoneconfig) ]; then
+                  echo -e "$boldred--- $(zoneconfig) was not found ---$reset"
+                  echo "##vso[task.logissue type=error]File $(zoneconfig) was not found."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_CLIENT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_CLIENT_SECRET) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                  exit 2
+                fi
+                if [ ! -n $(ARM_TENANT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                  exit 2
+                fi
+              echo -e "$green--- Set DEPLOYMENT_REPO_PATH variable and ---$reset"
+              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
+                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+              echo -e "$green--- az login ---$reset"
+                export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
+                export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
+                export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
+                export ARM_TENANT_ID=$(ARM_TENANT_ID)
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo -e "$boldred--- Login failed ---$reset"
+                  echo "##vso[task.logissue type=error]az login failed."
+                  exit $return_code
+                fi
+                az account set --subscription $(ARM_SUBSCRIPTION_ID)
+              echo -e "$green--- --- Convert config file to UX format ---$reset"
+                sudo apt-get -qq install dos2unix
+                dos2unix -q LANDSCAPE/$(zonefolder)/$(zoneconfig)
+              echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
+                organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
+                git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
+              echo -e "$green--- Run the install workloadzone script that deploys the SAP networks ---$reset"
+                cd $HOME/LANDSCAPE/$(zonefolder)
+                $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(zoneconfig) --deployer_environment $(env) --subscription $(ARM_SUBSCRIPTION_ID) --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID) --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${keyvault}" --storageaccountname "${REMOTE_STATE_SA}" --subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
+                return_code=$?
+              echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
+                cd $(Build.Repository.LocalPath)
+
+                git config --global user.email "$(Build.RequestedForEmail)"
+                git config --global user.name  "$(Build.RequestedFor)"
+                git pull origin $(Branch)                                                                             &>> /tmp/$(log)
+                added=0
+                if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA} ]; then
+                  git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}                &>>  /tmp/$(log)
+                  added=1
+                fi
+                if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
+                  git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}.md             &>>  /tmp/$(log)
+                  added=1
+                fi
+                if [ -f $(Deployment_Configuration_Path)/LANDSCAPE/$(zonefolder)/.terraform/terraform.tfstate ]; then
+                  git add -f $(Deployment_Configuration_Path)/LANDSCAPE/$(zonefolder)/.terraform/terraform.tfstate    &>> /tmp/$(log)
+                  added=1
+                fi
+                if [ 1 == $added ]; then
+                  git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"              &>> /tmp/$(log)
+
+                  git push origin HEAD:$(Branch)                                                                      &>> /tmp/$(log)
+                fi
+              echo "output the log ---$reset"
+                cat /tmp/$(log)
+                if [ -f $HOME/.sap_deployment_automation/${ENV}${LOCA}.md ]; then
+                  echo "##vso[task.uploadsummary]$HOME/.sap_deployment_automation/${ENV}${LOCA}.md"
+                fi
+                git config --unset-all http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader
+                exit $return_code
+            displayName: Deploy SAP Workload Zone
+            env:
+              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+            failOnStderr: true
diff --git a/deploy/pipelines/03-sap-system-deployment.yaml b/deploy/pipelines/03-sap-system-deployment.yaml
--- a/deploy/pipelines/03-sap-system-deployment.yaml
+++ b/deploy/pipelines/03-sap-system-deployment.yaml
@@ -1,13 +1,12 @@
 # This pipeline performs the SAP systems and storage deployments
 
 parameters:
-- name: sap_system
-  displayName: ENV-LOCA-VNET-SID
-  type: string
-  default: DEV-WEEU-SAP01-X00
+  - name: sap_system
+    displayName: ENV-LOCA-VNET-SID
+    type: string
+    default: DEV-WEEU-SAP01-X00
 
-trigger:
-  none
+trigger: none
 
 pool:
   vmImage: ubuntu-latest
@@ -16,102 +15,102 @@ variables:
   sapsystemfolder: ${{ parameters.sap_system }}
   sapsystemconfig: ${{ parameters.sap_system }}.tfvars
   log: logfile_$(Build.BuildId)
-  tf_version: '1.0.11'
+  tf_version: "1.0.11"
   tf_url: https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip
 
-name: $(sapsystemfolder)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
+name: SAP Infrastructure Deployment $(sapsystemfolder) [$(Date:yyyyMMdd)
 
 stages:
-- stage: Deploy_SAP_infrastructure
-  displayName: Deploy SAP infrastructure
-  jobs:
-  - job: Deploy_SAP_infrastructure
-    steps:
-    - script: |
-        #!/bin/bash
-        green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
-        echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-          export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-          export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
-          cd $HOME; mkdir -p .sap_deployment_automation
-          echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
-        echo -e "$green--- Validations ---$reset"
-        if [ ! -f $(sapsystemfolder) ]; then
-          echo -e "$boldred--- $(sapsystemfolder) was not found ---$reset"
-          echo "##vso[task.logissue type=error]File $(sapsystemfolder) was not found."
-          exit 2
-        fi
-        if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-          exit 2
-        fi
-        if [ ! -n $(ARM_CLIENT_ID) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-          exit 2
-        fi
-        if [ ! -n $(ARM_CLIENT_SECRET) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-          exit 2
-        fi
-        if [ ! -n $(ARM_TENANT_ID) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-          exit 2
-        fi
-        SID=$(echo $(sapsystemfolder) | cut -d'-' -f4 | xargs) 
-        if [ ! -n $(SID) ]; then
-          echo "##vso[task.logissue type=error]SID was not defined in the parameter file."
-          exit 2
-        fi
-        echo -e "$green--- Install Terraform ---$reset"
-          wget -q $(tf_url)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-            exit 2
-          fi
-          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
-        echo -e "$green--- Set DEPLOYMENT_REPO_PATH variable and ---$reset"
-        echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-          export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-        echo -e "$green--- az login ---$reset"
-          export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
-          export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
-          export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
-          export ARM_TENANT_ID=$(ARM_TENANT_ID)
-          az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo -e "$boldred--- Login failed ---$reset"
-            echo "##vso[task.logissue type=error]az login failed."
-            exit $return_code
-          fi
+  - stage: Deploy_SAP_infrastructure
+    displayName: Deploy SAP infrastructure
+    jobs:
+      - job: Deploy_SAP_infrastructure
+        steps:
+          - script: |
+              #!/bin/bash
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
+                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
+                cd $HOME; mkdir -p .sap_deployment_automation
+                echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+              echo -e "$green--- Validations ---$reset"
+              if [ ! -f $(sapsystemfolder) ]; then
+                echo -e "$boldred--- $(sapsystemfolder) was not found ---$reset"
+                echo "##vso[task.logissue type=error]File $(sapsystemfolder) was not found."
+                exit 2
+              fi
+              if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                exit 2
+              fi
+              if [ ! -n $(ARM_CLIENT_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                exit 2
+              fi
+              if [ ! -n $(ARM_CLIENT_SECRET) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                exit 2
+              fi
+              if [ ! -n $(ARM_TENANT_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                exit 2
+              fi
+              SID=$(echo $(sapsystemfolder) | cut -d'-' -f4 | xargs) 
+              if [ ! -n $(SID) ]; then
+                echo "##vso[task.logissue type=error]SID was not defined in the parameter file."
+                exit 2
+              fi
+              echo -e "$green--- Install Terraform ---$reset"
+                wget -q $(tf_url)
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+                  exit 2
+                fi
+                unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+              echo -e "$green--- Set DEPLOYMENT_REPO_PATH variable and ---$reset"
+              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
+                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+              echo -e "$green--- az login ---$reset"
+                export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
+                export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
+                export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
+                export ARM_TENANT_ID=$(ARM_TENANT_ID)
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo -e "$boldred--- Login failed ---$reset"
+                  echo "##vso[task.logissue type=error]az login failed."
+                  exit $return_code
+                fi
 
-          az account set --subscription $(ARM_SUBSCRIPTION_ID)
-        echo -e "$green--- --- Convert config file to UX format ---$reset"
-          sudo apt-get -qq install dos2unix
-          dos2unix -q SYSTEM/$(sapsystemfolder)/$(sapsystemconfig)
-        echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
-          organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
-          git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
-        echo -e "$green--- Run the installer script that deploys the SAP System ---$reset"
-          cd $HOME/SYSTEM/$(sapsystemfolder)
-          ${DEPLOYMENT_REPO_PATH}/deploy/scripts/installer.sh --parameterfile $(sapsystemconfig) --type sap_system --ado --auto-approve
-          return_code=$?
-        echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
-          cd $(Build.Repository.LocalPath)
-          git config --global user.email "$(Build.RequestedForEmail)"
-          git config --global user.name "$(Build.RequestedFor)" 
-          git add -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/.terraform/terraform.tfstate  &>  /tmp/$(log)
-          git add    $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/sap-parameters.yaml           &>> /tmp/$(log)
-          git add    $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/${SID}_hosts.yaml             &>> /tmp/$(log)
-          git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"              &>> /tmp/$(log)
-          git pull origin $(Branch)                                                                           &>> /tmp/$(log)
-          git push origin HEAD:$(Branch)                                                                      &>> /tmp/$(log)
-        echo "output the log ---$reset"
-          cat /tmp/$(log)
-          git config --unset-all http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader
-          exit $return_code
-      displayName: Deploy_SAP_infrastructure
-      env:
-        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-      failOnStderr: true
+                az account set --subscription $(ARM_SUBSCRIPTION_ID)
+              echo -e "$green--- --- Convert config file to UX format ---$reset"
+                sudo apt-get -qq install dos2unix
+                dos2unix -q SYSTEM/$(sapsystemfolder)/$(sapsystemconfig)
+              echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
+                organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
+                git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
+              echo -e "$green--- Run the installer script that deploys the SAP System ---$reset"
+                cd $HOME/SYSTEM/$(sapsystemfolder)
+                ${DEPLOYMENT_REPO_PATH}/deploy/scripts/installer.sh --parameterfile $(sapsystemconfig) --type sap_system --ado --auto-approve
+                return_code=$?
+              echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
+                cd $(Build.Repository.LocalPath)
+                git config --global user.email "$(Build.RequestedForEmail)"
+                git config --global user.name "$(Build.RequestedFor)" 
+                git add -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/.terraform/terraform.tfstate  &>  /tmp/$(log)
+                git add    $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/sap-parameters.yaml           &>> /tmp/$(log)
+                git add    $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/${SID}_hosts.yaml             &>> /tmp/$(log)
+                git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"              &>> /tmp/$(log)
+                git pull origin $(Branch)                                                                           &>> /tmp/$(log)
+                git push origin HEAD:$(Branch)                                                                      &>> /tmp/$(log)
+              echo "output the log ---$reset"
+                cat /tmp/$(log)
+                git config --unset-all http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader
+                exit $return_code
+            displayName: Deploy_SAP_infrastructure
+            env:
+              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+            failOnStderr: true
diff --git a/deploy/pipelines/04-sap-software-download.yaml b/deploy/pipelines/04-sap-software-download.yaml
--- a/deploy/pipelines/04-sap-software-download.yaml
+++ b/deploy/pipelines/04-sap-software-download.yaml
@@ -1,30 +1,29 @@
 # This pipeline performs the software download
-# and need to run on a self hosted deployment agent 
+# and need to run on a self hosted deployment agent
 # due to long run time
 
 parameters:
-- name: bom_base_name
-  displayName: Name of Bill of Materials (BoM)
-  type: string
-  default: S41909SPS03_v0007ms
-  values:
-   - S41909SPS03_v0007ms
-   - BW4HANA2021SPS01_v0001ms
-   - HANA_2_00_055_v0005ms
-   - NW750SPS20_v0002ms
+  - name: bom_base_name
+    displayName: Name of Bill of Materials (BoM)
+    type: string
+    default: S41909SPS03_v0007ms
+    values:
+      - S41909SPS03_v0007ms
+      - BW4HANA2021SPS01_v0001ms
+      - HANA_2_00_055_v0005ms
+      - NW750SPS20_v0002ms
 
-- name: environment
-  displayName: Control Plane Environment
-  type: string
-  default: MGMT
+  - name: environment
+    displayName: Control Plane Environment
+    type: string
+    default: MGMT
 
-- name: region
-  displayName: Control Plane (SAP Library) Locationcode
-  type: string
-  default: WEEU
+  - name: region
+    displayName: Control Plane (SAP Library) Locationcode
+    type: string
+    default: WEEU
 
-trigger:
-  none
+trigger: none
 
 pool:
   name: $(agent)
@@ -34,91 +33,88 @@ variables:
   env: ${{ parameters.environment }}
   loc: ${{ parameters.region }}
 
-name: $(bom)_$(env)_$(loc)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
+name: SAP Software download $(bom) $(env)_$(loc) [$(Date:yyyyMMdd)
 
 stages:
-- stage: Prepare_download
-  displayName: Preparation
-  jobs:
-  - job: Prepare_download
+  - stage: Prepare_download
     displayName: Preparation
-    steps:
-    - script: |
-        #!/bin/bash
-        green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
-        echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-          export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-          export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
-          cd $HOME; mkdir -p .sap_deployment_automation
-          echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
-        echo -e "$green--- Validations ---$reset"
-        if [ ! -f .sap_deployment_automation/$(env)$(loc) ]; then
-          echo -e "$boldred--- .sap_deployment_automation/$(env)$(loc) was not found ---$reset"
-          echo "##vso[task.logissue type=error]File .sap_deployment_automation/$(env)$(loc) was not found."
-          exit 2
-        fi
-        if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-          exit 2
-        fi
-        if [ ! -n $(ARM_CLIENT_ID) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-          exit 2
-        fi
-        if [ ! -n $(ARM_CLIENT_SECRET) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-          exit 2
-        fi
-        if [ ! -n $(ARM_TENANT_ID) ]; then
-          echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-          exit 2
-        fi
-        ls $(Build.Repository.LocalPath)
-        cat $(Build.Repository.LocalPath)/deploy/ansible/playbook_bom_downloader.yaml
-        echo -e "$green--- az login ---$reset"
-          az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
-          az account set --subscription $(ARM_SUBSCRIPTION_ID)
-        echo -e "$green--- Convert config files to UX format ---$reset"
-          sudo apt-get -qq install dos2unix
-          dos2unix -q $HOME/BOMS/sap-parameters.yaml
-          kv_name=$(cat .sap_deployment_automation/$(env)$(loc) | grep keyvault |awk -F'=' '{print $2}')
-          sapbits_sa_url=$(az keyvault secret show --vault-name $kv_name --name sapbits-location-base-path --query value |xargs)
-          sed -i 's|bom_base_name:.*|bom_base_name:   '"$(bom)"'|' BOMS/sap-parameters.yaml
-          sed -i 's|sapbits_location_base_path:.*|sapbits_location_base_path:    '"$sapbits_sa_url"'|' BOMS/sap-parameters.yaml
-          sed -i 's|kv_name:.*|kv_name:    '"$kv_name"'|' BOMS/sap-parameters.yaml
-        echo -e "$green--- Content of BOMS/sap-parameters.yaml ---$reset"
-          cat $HOME/BOMS/sap-parameters.yaml
-        echo -e "$green--- Set S-Username and S-Password in the key_vault if not yet there ---$reset"
-          export SUsername=$(az keyvault secret list --vault-name $kv_name --query [].name -o tsv | grep S-Username | xargs)
-          echo $SUsername
-          if [ -z "$SUsername" ]; then 
-            az keyvault secret set --output none --name S-Username --vault-name $kv_name --value $(S-Username)
-          fi
-          export SPassword=$(az keyvault secret list --vault-name $kv_name --query [].name -o tsv | grep S-Password | xargs)
-          if [ -z "$SPassword" ]; then 
-            az keyvault secret set --output none --name S-Password --vault-name $kv_name --value $(S-Password)
-          fi
-      displayName: Prepare download
-      env:
-          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-      failOnStderr: true
+    jobs:
+      - job: Prepare_download
+        displayName: Preparation
+        steps:
+          - script: |
+              #!/bin/bash
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
+                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
+                cd $HOME; mkdir -p .sap_deployment_automation
+                echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+              echo -e "$green--- Validations ---$reset"
+              if [ ! -f .sap_deployment_automation/$(env)$(loc) ]; then
+                echo -e "$boldred--- .sap_deployment_automation/$(env)$(loc) was not found ---$reset"
+                echo "##vso[task.logissue type=error]File .sap_deployment_automation/$(env)$(loc) was not found."
+                exit 2
+              fi
+              if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                exit 2
+              fi
+              if [ ! -n $(ARM_CLIENT_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                exit 2
+              fi
+              if [ ! -n $(ARM_CLIENT_SECRET) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                exit 2
+              fi
+              if [ ! -n $(ARM_TENANT_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                exit 2
+              fi
+              ls $(Build.Repository.LocalPath)
+              cat $(Build.Repository.LocalPath)/deploy/ansible/playbook_bom_downloader.yaml
+              echo -e "$green--- az login ---$reset"
+                az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+                az account set --subscription $(ARM_SUBSCRIPTION_ID)
+              echo -e "$green--- Convert config files to UX format ---$reset"
+                sudo apt-get -qq install dos2unix
+                dos2unix -q $HOME/BOMS/sap-parameters.yaml
+                kv_name=$(cat .sap_deployment_automation/$(env)$(loc) | grep keyvault |awk -F'=' '{print $2}')
+                sapbits_sa_url=$(az keyvault secret show --vault-name $kv_name --name sapbits-location-base-path --query value |xargs)
+                sed -i 's|bom_base_name:.*|bom_base_name:   '"$(bom)"'|' BOMS/sap-parameters.yaml
+                sed -i 's|sapbits_location_base_path:.*|sapbits_location_base_path:    '"$sapbits_sa_url"'|' BOMS/sap-parameters.yaml
+                sed -i 's|kv_name:.*|kv_name:    '"$kv_name"'|' BOMS/sap-parameters.yaml
+              echo -e "$green--- Content of BOMS/sap-parameters.yaml ---$reset"
+                cat $HOME/BOMS/sap-parameters.yaml
+              echo -e "$green--- Set S-Username and S-Password in the key_vault if not yet there ---$reset"
+                export SUsername=$(az keyvault secret list --vault-name $kv_name --query [].name -o tsv | grep S-Username | xargs)
+                echo $SUsername
+                if [ -z "$SUsername" ]; then 
+                  az keyvault secret set --output none --name S-Username --vault-name $kv_name --value $(S-Username)
+                fi
+                export SPassword=$(az keyvault secret list --vault-name $kv_name --query [].name -o tsv | grep S-Password | xargs)
+                if [ -z "$SPassword" ]; then 
+                  az keyvault secret set --output none --name S-Password --vault-name $kv_name --value $(S-Password)
+                fi
+            displayName: Prepare download
+            env:
+              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+            failOnStderr: true
 
-- stage: Software_download
-  displayName: Download software
-  jobs:
-  - job: Software_download
+  - stage: Software_download
     displayName: Download software
-    timeoutInMinutes: 0
-    steps:
-    - checkout: none
-    - task: Ansible@0
-      displayName: Download software
-      timeoutInMinutes: 0
-      inputs:
-        ansibleInterface: 'agentMachine'
-        playbookPathOnAgentMachine:  $(Build.Repository.LocalPath)/deploy/ansible/playbook_bom_downloader.yaml
-        args: '-e "HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)" -e "@$(Deployment_Configuration_Path)/BOMS/sap-parameters.yaml" -e "_workspace_directory=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)/BOMS" '
-        failOnStderr: true
-        
-
-        
+    jobs:
+      - job: Software_download
+        displayName: Download software
+        timeoutInMinutes: 0
+        steps:
+          - checkout: none
+          - task: Ansible@0
+            displayName: Download software
+            timeoutInMinutes: 0
+            inputs:
+              ansibleInterface: "agentMachine"
+              playbookPathOnAgentMachine: $(Build.Repository.LocalPath)/deploy/ansible/playbook_bom_downloader.yaml
+              args: '-e "HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)" -e "@$(Deployment_Configuration_Path)/BOMS/sap-parameters.yaml" -e "_workspace_directory=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)/BOMS" '
+              failOnStderr: true
