tests

diff --git a/deploy/pipelines/01-prepare-region.yaml b/deploy/pipelines/01-prepare-region.yaml
--- a/deploy/pipelines/01-prepare-region.yaml
+++ b/deploy/pipelines/01-prepare-region.yaml
@@ -38,20 +38,29 @@ stages:
     - script: |
         #!/bin/bash
         green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+
+        echo -e "$green--- Install Terraform ---$reset"
+          wget -q $(tf_url)
+          return_code=$?
+          if [ 0 != $return_code ]; then
+            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+            exit 2
+          fi
+          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+
         echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
           export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
           export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
           cd $HOME; mkdir -p .sap_deployment_automation
           echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+
         echo -e "$green--- Validations ---$reset"
-        echo LIBRARY/$(libraryfolder)/$(libraryconfig)
-        echo DEPLOYER/$(deployerfolder)/$(deployerconfig)
           if [ ! -f DEPLOYER/$(deployerfolder)/$(deployerconfig) ]; then
             echo -e "$boldred--- File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found ---$reset"
             echo "##vso[task.logissue type=error]File DEPLOYER/$(deployerfolder)/$(deployerconfig) was not found."
             exit 2
           fi
-          if [ ! -f LIBRARY/$(libraryfolder)/$(libraryconfig)  ]; then
+          if [ ! -f LIBRARY/$(libraryfolder)/$(libraryconfig) ]; then
             echo -e "$boldred--- File LIBRARY/$(libraryfolder)/$(libraryconfig)  was not found ---$reset"
             echo "##vso[task.logissue type=error]File LIBRARY/$(libraryfolder)/$(libraryconfig) was not found."
             exit 2
@@ -72,14 +81,7 @@ stages:
             echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
             exit 2
           fi
-        echo -e "$green--- Install Terraform ---$reset"
-          wget -q $(tf_url)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-            exit 2
-          fi
-          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
+
         echo -e "$green--- az login ---$reset"
           export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
           export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
@@ -94,16 +96,20 @@ stages:
           fi
 
           az account set --subscription $(ARM_SUBSCRIPTION_ID)
+
         echo -e "$green--- Prepare the exchange of information from devops agent back to the repository ---$reset"
           organization=$(echo $(System.CollectionUri) | cut -d'/' -f4)
           git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
+
         echo -e "$green--- Convert config files to UX format ---$reset"
           sudo apt-get -qq install dos2unix
           dos2unix -q DEPLOYER/$(deployerfolder)/$(deployerconfig)
           dos2unix -q LIBRARY/$(libraryfolder)/$(libraryconfig) 
+
         echo -e "$green--- Running the prepare region script that deploys the subscription hub with the Deployer VM and SAP Library ---$reset"
-          $DEPLOYMENT_REPO_PATH/deploy/scripts/prepare_region.sh --deployer_parameter_file DEPLOYER/$(deployerfolder)/$(deployerconfig) --library_parameter_file LIBRARY/$(libraryfolder)/$(libraryconfig)  --subscription $(ARM_SUBSCRIPTION_ID)  --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID)  --auto-approve 2> /dev/null
+          $DEPLOYMENT_REPO_PATH/deploy/scripts/prepare_region.sh --deployer_parameter_file DEPLOYER/$(deployerfolder)/$(deployerconfig) --library_parameter_file LIBRARY/$(libraryfolder)/$(libraryconfig)  --subscription $(ARM_SUBSCRIPTION_ID)  --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID)  --auto-approve
           return_code=$?
+
         echo -e "$green--- Adding deployment automation configuration to devops repository ---$reset"
           cd $(Build.Repository.LocalPath)
           git config --global user.email "$(Build.RequestedForEmail)"
diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -37,10 +37,19 @@ stages:
     - script: |
         #!/bin/bash
         green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+        echo -e "$green--- Install Terraform ---$reset"
+          wget -q $(tf_url)
+          return_code=$?
+          if [ 0 != $return_code ]; then
+            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
+            exit 2
+          fi
+          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
         echo -e "$green--- Set WORKSPACES folder as new home ---$reset"
           export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
           cd $HOME; mkdir -p .sap_deployment_automation
           echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+          cd $HOME/LANDSCAPE/$(zonefolder)          
         echo -e "$green--- Validations ---$reset"
           if [ ! -f $(zoneconfig) ]; then
             echo -e "$boldred--- $(zoneconfig) was not found ---$reset"
@@ -63,14 +72,6 @@ stages:
             echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
             exit 2
           fi
-        echo -e "$green--- Install Terraform ---$reset"
-          wget -q $(tf_url)
-          return_code=$?
-          if [ 0 != $return_code ]; then
-            echo "##vso[task.logissue type=error]Unable to download Terraform version $(tf_version)."
-            exit 2
-          fi
-          unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
         echo -e "$green--- Set DEPLOYMENT_REPO_PATH variable and ---$reset"
         echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
           export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
