Misc fixes

diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -22,7 +22,6 @@ variables:
   zoneconfig: ${{ parameters.workloadzone }}.tfvars
   env: ${{ parameters.environment }}
   log: logfile_$(Build.BuildId)
-  tf_version: '1.0.11'
   tf_url: https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip
 
 name: $(zonefolder)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
@@ -49,9 +48,20 @@ stages:
           export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
           cd $HOME; mkdir -p .sap_deployment_automation
           echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
-          cd $HOME/LANDSCAPE/$(zonefolder)          
+          export ENV=$(echo $(zonefolder)  | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENV
+          export LOCA=$(echo $(zonefolder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCA
+          export deployer_tfstate_key=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep deployer_tfstate_key | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer State File' $deployer_tfstate_key
+          export keyvault=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep keyvault | awk -F'=' '{print $2}' | xargs) ; echo 'Deployer Key Vault' $keyvault
+          export REMOTE_STATE_SA=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep REMOTE_STATE_SA | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform statefile storage account' $REMOTE_STATE_SA
+          export STATE_SUBSCRIPTION=$(cat .sap_deployment_automation/$(env)${LOCA}  | grep STATE_SUBSCRIPTION | awk -F'=' '{print $2}' | xargs) ; echo 'Terraform statefile subscription' $STATE_SUBSCRIPTION
+       
         echo -e "$green--- Validations ---$reset"
-          if [ ! -f $(zoneconfig) ]; then
+          if [ ! -f $HOME/.sap_deployment_automation/$(env)$LOCA ]; then
+            echo -e "$boldred--- $(env)$LOCA was not found ---$reset"
+            echo "##vso[task.logissue type=error]Control plane configuration file $(env)$LOC was not found."
+            exit 2
+          fi
+          if [ ! -f $HOME/LANDSCAPE/$(zonefolder)/$(zoneconfig) ]; then
             echo -e "$boldred--- $(zoneconfig) was not found ---$reset"
             echo "##vso[task.logissue type=error]File $(zoneconfig) was not found."
             exit 2
@@ -96,14 +106,12 @@ stages:
           git config  http.https://$organization@dev.azure.com/$organization/$(System.TeamProject)/_git/$(Build.Repository.Name).extraheader "AUTHORIZATION: bearer $SYSTEM_ACCESSTOKEN"
         echo -e "$green--- Run the install workloadzone script that deploys the SAP networks ---$reset"
           cd $HOME/LANDSCAPE/$(zonefolder)
-          $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(zoneconfig) --deployer_environment $(env) --subscription $(ARM_SUBSCRIPTION_ID) --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID) --auto-approve
+          $DEPLOYMENT_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(zoneconfig) --deployer_environment $(env) --subscription $(ARM_SUBSCRIPTION_ID) --spn_id $(ARM_CLIENT_ID) --spn_secret $(ARM_CLIENT_SECRET) --tenant_id $(ARM_TENANT_ID) --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${keyvault}" --storageaccountname "${REMOTE_STATE_SA}" --subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
           return_code=$?
         echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
           cd $(Build.Repository.LocalPath)
           git config --global user.email "$(Build.RequestedForEmail)"
           git config --global user.name  "$(Build.RequestedFor)"
-          export ENV=$(echo $(zonefolder)  | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENV
-          export LOCA=$(echo $(zonefolder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCA
           git add    $(Deployment_Configuration_Path)/.sap_deployment_automation/${ENV}${LOCA}                  &>  /tmp/$(log)
           git add -f $(Deployment_Configuration_Path)/LANDSCAPE/$(zonefolder)/.terraform/terraform.tfstate      &>> /tmp/$(log)
           git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"                &>> /tmp/$(log)
