Rationalize login code, provide ARM_SUBSCRIPTION_ID as output

diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -481,6 +481,12 @@ stages:
                     export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
                     export ARM_USE_MSI=false
                     az login --service-principal --username $WL_ARM_CLIENT_ID --password=$WL_ARM_CLIENT_SECRET --tenant $WL_ARM_TENANT_ID --output none
+                    return_code=$?
+                    if [ 0 != $return_code ]; then
+                      echo -e "$boldred--- Login failed ---$reset"
+                      echo "##vso[task.logissue type=error]az login failed."
+                      exit $return_code
+                    fi
                   else
                     export ARM_USE_MSI=true
                     az login --identity --allow-no-subscriptions --output none
