Refactor deploy_controlplane.sh to use managed service identity (MSI) for authentication

diff --git a/deploy/pipelines/02-sap-workload-zone.yaml b/deploy/pipelines/02-sap-workload-zone.yaml
--- a/deploy/pipelines/02-sap-workload-zone.yaml
+++ b/deploy/pipelines/02-sap-workload-zone.yaml
@@ -402,42 +402,48 @@ stages:
               secrets_set=1
               echo -e "$green--- az login ---$reset"
 
-                if [ $LOGON_USING_SPN == "true" ]; then
-                  echo "Using SPN"
-                  az login --service-principal --username $CP_ARM_CLIENT_ID --password=$CP_ARM_CLIENT_SECRET --tenant $CP_ARM_TENANT_ID --output none
+                echo "Sourcing the deploy_server.sh"
+                . /etc/profile.d/deploy_server.sh ; /opt/bin/terraform/terraform --version
+
+                if [ $USE_MSI != "true" ]; then
+
+                    echo -e "$cyan--- Using SPN ---$reset"
+                    export ARM_CLIENT_ID=$WL_ARM_CLIENT_ID
+                    export ARM_CLIENT_SECRET=$WL_ARM_CLIENT_SECRET
+                    export ARM_TENANT_ID=$WL_ARM_TENANT_ID
+                    export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
+                    export ARM_USE_AZUREAD=true
+                    unset ARM_USE_MSI
+                    az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
+
+                    return_code=$?
+                    if [ 0 != $return_code ]; then
+                        echo -e "$boldred--- Login failed ---$reset"
+                        echo "##vso[task.logissue type=error]az login failed."
+                        exit $return_code
+                    fi
+                    az account set --subscription $STATE_SUBSCRIPTION
+                    echo -e "$green --- Set secrets ---$reset"
+
+                    $SAP_AUTOMATION_REPO_PATH/deploy/scripts/set_secrets.sh --workload --vault "${key_vault}" --environment "${ENVIRONMENT}"  \
+                      --region "${LOCATION}" --subscription $WL_ARM_SUBSCRIPTION_ID --spn_id $WL_ARM_CLIENT_ID --spn_secret "${WL_ARM_CLIENT_SECRET}"      \
+                      --tenant_id $WL_ARM_TENANT_ID --keyvault_subscription $STATE_SUBSCRIPTION
+                    secrets_set=$? ; echo -e "$cyan Set Secrets returned $secrets_set $reset"
+                    az keyvault set-policy --name "${key_vault}" --object-id $WL_ARM_OBJECT_ID --secret-permissions get list  --subscription $STATE_SUBSCRIPTION --output none
                 else
-                  echo "Using MSI"
-                  export ARM_USE_MSI=true
-                  export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
-                  unset ARM_TENANT_ID
-
-                  az login --identity --allow-no-subscriptions --output none
+                    echo -e "$cyan--- Using MSI ---$reset"
+                    # export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
+                    export ARM_USE_MSI=true
+                    export ARM_USE_AZUREAD=true
+                    unset ARM_CLIENT_SECRET
                 fi
-
-                return_code=$?
-                if [ 0 != $return_code ]; then
-                  echo -e "$boldred--- Login failed ---$reset"
-                  echo "##vso[task.logissue type=error]az login failed."
-                  exit $return_code
-                fi
-
-              if [ $USE_MSI != "true" ]; then
-                echo -e "$green --- Set secrets ---$reset"
-
-                $SAP_AUTOMATION_REPO_PATH/deploy/scripts/set_secrets.sh --workload --vault "${key_vault}" --environment "${ENVIRONMENT}"  \
-                  --region "${LOCATION}" --subscription $WL_ARM_SUBSCRIPTION_ID --spn_id $WL_ARM_CLIENT_ID --spn_secret "${WL_ARM_CLIENT_SECRET}"      \
-                  --tenant_id $WL_ARM_TENANT_ID --keyvault_subscription $STATE_SUBSCRIPTION
-                secrets_set=$? ; echo -e "$cyan Set Secrets returned $secrets_set $reset"
-                az keyvault set-policy --name "${key_vault}" --object-id $WL_ARM_OBJECT_ID --secret-permissions get list  --subscription $STATE_SUBSCRIPTION --output none
-              fi
 
               debug_variable='--output none'
               debug_variable=''
 
               if [ $USE_MSI != "true" ]; then
-                az login --service-principal --username $CP_ARM_CLIENT_ID --password=$CP_ARM_CLIENT_SECRET --tenant $CP_ARM_TENANT_ID --output none
 
-                isUserAccessAdmin=$(az role assignment list --role "User Access Administrator" --subscription $STATE_SUBSCRIPTION  --query "[?principalType=='ServicePrincipal'].principalId | [0] " --assignee $CP_ARM_CLIENT_ID)
+                isUserAccessAdmin=$(az role assignment list --role "User Access Administrator" --subscription $STATE_SUBSCRIPTION  --query "[?principalType=='ServicePrincipal'].principalId | [0] " --assignee $ARM_CLIENT_ID)
 
                 tfstate_resource_id=$(az resource list --name "${REMOTE_STATE_SA}" --subscription ${STATE_SUBSCRIPTION} --resource-type Microsoft.Storage/storageAccounts --query "[].id | [0]" -o tsv)
 
@@ -450,10 +456,10 @@ stages:
                       az role assignment create --assignee-object-id $WL_ARM_OBJECT_ID  --assignee-principal-type ServicePrincipal --role "Reader" --scope "/subscriptions/${STATE_SUBSCRIPTION}" --output none
                     fi
 
-                    perms=$(az role assignment list --subscription ${STATE_SUBSCRIPTION} --role "Storage Account Contributor" --scope "${tfstate_resource_id}" --query "[?principalId=='$WL_ARM_OBJECT_ID'].principalName | [0]" -o tsv  --only-show-errors)
+                    perms=$(az role assignment list --subscription ${STATE_SUBSCRIPTION} --role "Storage Blob Data Contributor" --scope "${tfstate_resource_id}" --query "[?principalId=='$WL_ARM_OBJECT_ID'].principalName | [0]" -o tsv  --only-show-errors)
                     if [ -z "$perms" ]; then
                       echo "Assigning Storage Account Contributor permissions for $WL_ARM_OBJECT_ID to ${tfstate_resource_id}"
-                      az role assignment create --assignee-object-id $WL_ARM_OBJECT_ID  --assignee-principal-type ServicePrincipal --role "Storage Account Contributor" --scope "${tfstate_resource_id}" --output none
+                      az role assignment create --assignee-object-id $WL_ARM_OBJECT_ID  --assignee-principal-type ServicePrincipal --role "Storage Blob Data Contributor" --scope "${tfstate_resource_id}" --output none
                     fi
 
                     resource_group_name=$(az resource show --id "${tfstate_resource_id}" --query resourceGroup -o tsv)
@@ -484,34 +490,13 @@ stages:
                       fi
                   fi
                 else
-                  echo "##vso[task.logissue type=warning]Service Principal $CP_ARM_CLIENT_ID does not have 'User Access Administrator' permissions. Please ensure that the service principal $WL_ARM_CLIENT_ID has permissions on the Terrafrom state storage account and if needed on the Private DNS zone and the source management network resource"
+                  echo "##vso[task.logissue type=warning]Service Principal $WL_ARM_CLIENT_ID does not have 'User Access Administrator' permissions. Please ensure that the service principal $WL_ARM_CLIENT_ID has permissions on the Terrafrom state storage account and if needed on the Private DNS zone and the source management network resource"
                 fi
               fi
 
               echo -e "$green--- Deploy the workload zone ---$reset"
                 cd $CONFIG_REPO_PATH/LANDSCAPE/$(workload_zone_folder)
                 if [ -f /etc/profile.d/deploy_server.sh ]; then
-                  if [ $LOGON_USING_SPN == "true" ]; then
-                    echo "Logon Using SPN"
-
-                    az logout --output none
-                    export ARM_CLIENT_ID=$WL_ARM_CLIENT_ID
-                    export ARM_CLIENT_SECRET=$WL_ARM_CLIENT_SECRET
-                    export ARM_TENANT_ID=$WL_ARM_TENANT_ID
-                    export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
-                    export ARM_USE_MSI=false
-                    az login --service-principal --username $WL_ARM_CLIENT_ID --password=$WL_ARM_CLIENT_SECRET --tenant $WL_ARM_TENANT_ID --output none
-                    return_code=$?
-                    if [ 0 != $return_code ]; then
-                      echo -e "$boldred--- Login failed ---$reset"
-                      echo "##vso[task.logissue type=error]az login failed."
-                      exit $return_code
-                    fi
-                  else
-                    export ARM_USE_MSI=true
-                    az login --identity --allow-no-subscriptions --output none
-                  fi
-                else
                   if [ $USE_MSI != "true" ]; then
                     az logout --output none
                     export ARM_CLIENT_ID=$WL_ARM_CLIENT_ID
@@ -526,21 +511,19 @@ stages:
                       echo "##vso[task.logissue type=error]az login failed."
                       exit $return_code
                     fi
-                  fi
-
-                fi
-
-                if [ $USE_MSI != "true" ]; then
                   $SAP_AUTOMATION_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)   \
                     --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
                     --spn_id $WL_ARM_CLIENT_ID --spn_secret $WL_ARM_CLIENT_SECRET --tenant_id $WL_ARM_TENANT_ID                          \
                     --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${key_vault}" --storageaccountname "${REMOTE_STATE_SA}" \
                     --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado
-                else
-                  $SAP_AUTOMATION_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)   \
-                    --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
-                    --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${key_vault}" --storageaccountname "${REMOTE_STATE_SA}" \
-                    --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado --msi
+                  else
+                    $SAP_AUTOMATION_REPO_PATH/deploy/scripts/install_workloadzone.sh --parameterfile $(workload_zone_configuration_file)   \
+                      --deployer_environment $(deployer_environment) --subscription $(ARM_SUBSCRIPTION_ID)                                 \
+                      --deployer_tfstate_key "${deployer_tfstate_key}" --keyvault "${key_vault}" --storageaccountname "${REMOTE_STATE_SA}" \
+                      --state_subscription "${STATE_SUBSCRIPTION}" --auto-approve --ado --msi
+
+                  fi
+
                 fi
                 return_code=$?
 
@@ -552,7 +535,6 @@ stages:
                 fi
 
                 expiry_date=$(date -d "+365 days" +%Y-%m-%d)
-
 
                 az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "FENCING_SPN_ID.value")
                 if [ -z ${az_var} ]; then
