Ansible pipeline updates

diff --git a/deploy/pipelines/04-sap-software-download.yaml b/deploy/pipelines/04-sap-software-download.yaml
--- a/deploy/pipelines/04-sap-software-download.yaml
+++ b/deploy/pipelines/04-sap-software-download.yaml
@@ -52,14 +52,24 @@ pool:
 variables:
   - group:                             "SDAF-General"
   - group:                             SDAF-${{ parameters.environment }}
+
   - name:                              bom
     value:                             $[coalesce(variables['BoM_OverRide'], '${{ parameters.bom_base_name }}','foo')]
+
   - name:                              environment_code
     value:                             ${{ parameters.environment }}
+
   - name:                              location_code
     value:                             ${{ parameters.region }}
+
   - name:                              check_storage_account
     value:                             $[not(${{ parameters.re_download }})]
+
+  - name:                              this_agent
+    value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]
+
+  - name:                              key_vault
+    value:                             $[variables['Deployer_Key_Vault']]
 
 stages:
   - stage:                             Prepare_download
@@ -77,9 +87,8 @@ stages:
               #!/bin/bash
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
 
-
               echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+                
                 export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
                 environment_file_name=$HOME/.sap_deployment_automation/$(environment_code)$(location_code)
                 cd $HOME; mkdir -p .sap_deployment_automation
@@ -91,32 +100,32 @@ stages:
                 echo "##vso[task.logissue type=error]File ${environment_file_name} was not found."
                 exit 2
               fi
+              if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                exit 2
+              fi
+
+              if [[ "azure pipelines" == $(this_agent) ]]; then
+                echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-$(environment_code) variable group"
+                exit 2
+              fi
+              
+              if [ ! -n $(ARM_CLIENT_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                exit 2
+              fi
+
+              if [ ! -n $(ARM_CLIENT_SECRET) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                exit 2
+              fi
+
+              if [ ! -n $(ARM_TENANT_ID) ]; then
+                echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                exit 2
+              fi
 
               echo -e "$green--- az login ---$reset"
-                if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-                  exit 2
-                fi
-
-                if [ "Azure Pipelines" == $(Agent) ]; then
-                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-$(environment_code) variable group"
-                  exit 2
-                fi
-                
-                if [ ! -n $(ARM_CLIENT_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-                  exit 2
-                fi
-
-                if [ ! -n $(ARM_CLIENT_SECRET) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-                  exit 2
-                fi
-
-                if [ ! -n $(ARM_TENANT_ID) ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-                  exit 2
-                fi
 
                 az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID) --output none
                 return_code=$?
@@ -129,7 +138,12 @@ stages:
                 az account set --subscription $(ARM_SUBSCRIPTION_ID)
               echo -e "$green--- Get key_vault name ---$reset"
 
-                kv_name=$(cat .sap_deployment_automation/$(environment_code)$(location_code) | grep keyvault |awk -F'=' '{print $2}')
+                if [ -z "$key_vault" ]; then
+                    kv_name=$(cat .sap_deployment_automation/$(environment_code)$(location_code) | grep keyvault |awk -F'=' '{print $2}'); echo "Key Vault="$kv_name
+                else
+                  kv_name=$(key_vault); echo "Key Vault="$kv_name
+                fi
+                
                 echo "##vso[task.setvariable variable=KV_NAME;isOutput=true]$kv_name"
               
               echo -e "$green--- BoM $(bom) ---$reset"
@@ -161,6 +175,9 @@ stages:
             name:                      Preparation
             env:
               SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
+              ARM_CLIENT_ID:           $(ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
+              ARM_TENANT_ID:           $(ARM_TENANT_ID)
             failOnStderr:              false
 
   - stage:                             Software_download
@@ -238,5 +255,9 @@ stages:
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_PYTHON_INTERPRETER:    auto_silent
+              DEPLOYMENT_REPO_PATH:          $(Build.Repository.LocalPath)
+              ARM_CLIENT_ID:                 $(ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:             $(ARM_CLIENT_SECRET)
+              ARM_TENANT_ID:                 $(ARM_TENANT_ID)
 
 ...
diff --git a/deploy/pipelines/05-DB-and-SAP-installation.yaml b/deploy/pipelines/05-DB-and-SAP-installation.yaml
--- a/deploy/pipelines/05-DB-and-SAP-installation.yaml
+++ b/deploy/pipelines/05-DB-and-SAP-installation.yaml
@@ -91,12 +91,21 @@ trigger:                               none
 variables:
   - group:                             "SDAF-General"
   - group:                             SDAF-${{ parameters.environment }}
+
   - name:                              sap_system_folder
     value:                             ${{ parameters.sap_system_configuration_name }}
+
   - name:                              bom
     value:                             ${{ parameters.bom_base_name }}
+
   - name:                              agent_name
     value:                             $[coalesce(variables['POOL'], variables['Agent'])]
+
+  - name:                              this_agent
+    value:                             $[lower(coalesce(variables['POOL'], variables['Agent']))]
+
+  - name:                              variable_group
+    value:                             SDAF-${{ parameters.environment }}
 
 pool:
   name:                                $[coalesce(variables['POOL'], variables['Agent'])]
@@ -122,18 +131,29 @@ stages:
                 export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
                 cd $HOME
 
+              echo -e "$green--- Configure devops CLI extension ---$reset"
+                az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1
+                az devops configure -d organization=$(System.CollectionUri)
+                az devops configure -d project=$(System.TeamProject)
+                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
+
+                export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
+                echo '$(variable_group) id: ' $VARIABLE_GROUP_ID
+                if [ -z ${VARIABLE_GROUP_ID} ]; then
+                    echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
+                    exit 2
+                fi
+
               echo -e "$green--- Validations ---$reset"
                 ENVIRONMENT=$(echo $(sap_system_folder) | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENVIRONMENT
                    LOCATION=$(echo $(sap_system_folder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCATION
-                VIRTUAL_NET=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo Virtual network logical name $VIRTUAL_NET
+                    NETWORK=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo Virtual network logical name $NETWORK
                         SID=$(echo $(sap_system_folder) | awk -F'-' '{print $4}' | xargs) ; echo SID $SID
 
-                environment_file_name=$HOME/.sap_deployment_automation/$ENVIRONMENT$LOCATION ; echo configuration_file $environment_file_name
-                          params_file=$HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml ;  echo sap_parameters_file $params_file
+                environment_file_name=$HOME/.sap_deployment_automation/$ENVIRONMENT$LOCATION$NETWORK ; echo configuration_file $environment_file_name
+                          params_file=$HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml              ;  echo sap_parameters_file $params_file
 
-                agent_name=$(echo $(agent_name) | tr '[:upper:]' '[:lower:]')
-
-                if [[ "azure pipelines" == "${agent_name}" ]]; then
+              if [[ "azure pipelines" == $(this_agent) ]]; then
                   echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-${ENVIRONMENT} variable group"
                   exit 2
                 fi
@@ -174,22 +194,22 @@ stages:
                 echo "##vso[task.setvariable variable=CONFIGURATION_NAME;isOutput=true]$(sap_system_folder)"
 
               echo -e "$green--- az login ---$reset"
-                if [ ! -n $(ARM_SUBSCRIPTION_ID) ]; then
+                if [ -z $(ARM_SUBSCRIPTION_ID) ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
                   exit 2
                 fi
 
-                if [ ! -n $(ARM_CLIENT_ID) ]; then
+                if [ -z $(ARM_CLIENT_ID) ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
                   exit 2
                 fi
 
-                if [ ! -n $(ARM_CLIENT_SECRET) ]; then
+                if [ -z $(ARM_CLIENT_SECRET) ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
                   exit 2
                 fi
 
-                if [ ! -n $(ARM_TENANT_ID) ]; then
+                if [ -z $(ARM_TENANT_ID) ]; then
                   echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
                   exit 2
                 fi
@@ -213,12 +233,14 @@ stages:
               echo -e "$green--- Get sshkey to connect to SAP VMs ---$reset"
                 mkdir -p artifacts
 
-                if [ -n $(Workload_Key_Vault) ]; then
-                  export workload_key_vault=$(Workload_Key_Vault) ; echo 'Workload Key Vault' ${workload_key_vault}
-                else
+                az_var=$(az pipelines variable-group variable list --group-id ${VARIABLE_GROUP_ID} --query "${NETWORK}"Workload_Key_Vault.value | tr -d \")
+                if [ -z ${az_var} ]; then
                   export workload_key_vault=$(cat "${environment_file_name}"  | grep workload_key_vault      | awk -F'=' '{print $2}' | xargs) ; echo 'Workload Key Vault' ${workload_key_vault}
+                else
+                  export workload_key_vault=${az_var} ; echo 'Workload Key Vault' ${workload_key_vault}
                 fi
-                az keyvault secret show --name ${ENVIRONMENT}-${LOCATION}-${VIRTUAL_NET}-sid-sshkey --vault-name $workload_key_vault --query value -o tsv > artifacts/$(sap_system_folder)_sshkey
+
+                az keyvault secret show --name ${ENVIRONMENT}-${LOCATION}-${NETWORK}-sid-sshkey --vault-name $workload_key_vault --query value -o tsv > artifacts/$(sap_system_folder)_sshkey
                 cp sap-parameters.yaml artifacts/.
                 cp ${SID}_hosts.yaml artifacts/.
 
