Merged PR 8320960: Merging sap-automation main into this repo's main branch.
This is done as part of the 3.8.3 parity task. This is an attempt to bring the Co-Dev model into effect so that all ansible development can now happen through the SDAF-ASCS repo.

Related work items: #24291278

diff --git a/deploy/pipelines/04-sap-software-download.yaml b/deploy/pipelines/04-sap-software-download.yaml
--- a/deploy/pipelines/04-sap-software-download.yaml
+++ b/deploy/pipelines/04-sap-software-download.yaml
@@ -8,27 +8,6 @@ parameters:
   - name:                              bom_base_name
     displayName:                       Name of Bill of Materials (BoM)
     type:                              string
-    default:
-    values:
-      - S4HANA_2021_ISS_v0001ms
-      - S42020SPS04_v0001ms
-      - S41909SPS03_v0011ms
-      - HCMT_v0002ms
-      - BW4HANA2021SPS01_v0003ms
-      - HANA_2_00_063_v0001ms
-      - HANA_2_00_061_v0001ms
-      - HANA_2_00_059_v0003ms
-      - HANA_2_00_055_v0006ms
-      - NW750SPS20_v0004ms
-      - NW752SPS09_v0001ms
-      - ⁠NW750SPS20_DB2_v0001ms
-      - ORACLE_19_00_v0002ms
-      - ORACLE_19_00_v0003ms
-      - NW750SPS20_DB2_v0001ms
-      - DB2_UDB_11_5_v0001ms
-      - ORACLE_19_00_ORA_MSID_v0001ms
-      - ORACLE_19_00_ORA_MSID_v0002ms
-      - ERP6_EHP8_WIN_MSS2019_v0001ms
 
   - name:                              environment
     displayName:                       Control Plane Environment
@@ -54,6 +33,10 @@ parameters:
 
   - name:                              sample_repo_path
     displayName:                       The local path on the agent where the config repo can be found
+    type:                              string
+
+  - name:                              ExtraParams
+    displayName:                       Extra parameters to pass to Ansible
     type:                              string
 
 stages:
@@ -145,23 +128,23 @@ stages:
               echo -e "$green--- Set S-Username and S-Password in the key_vault if not yet there ---$reset"
 
                 export SUsernamefromVault=$(az keyvault secret list --vault-name "${kv_name}" --subscription "${ARM_SUBSCRIPTION_ID}" --query "[].{Name:name} | [? contains(Name,'S-Username')] | [0]"  -o tsv)
-                if [ -z $SUsernamefromVault ]; then
+                if [ $SUsernamefromVault == $SUsername ]; then
+                  echo -e "$green--- $SUsername present in keyvault. In case of download errors check that user and password are correct ---$reset"
+                  echo "##vso[task.setvariable variable=SUSERNAME;isOutput=true]$SUsernamefromVault"
+                else
                   echo -e "$green--- Setting the S username in key vault ---$reset"
                   az keyvault secret set --name "S-Username" --vault-name $kv_name --value="${SUsername}" --subscription "${ARM_SUBSCRIPTION_ID}" --output none
                   echo "##vso[task.setvariable variable=SUSERNAME;isOutput=true]$SUsername"
-                else
-                  echo -e "$green--- $SUsername present in keyvault. In case of download errors check that user and password are correct ---$reset"
-                  echo "##vso[task.setvariable variable=SUSERNAME;isOutput=true]$SUsernamefromVault"
                 fi
 
                 export SPasswordfromVault=$(az keyvault secret list --vault-name "${kv_name}" --subscription "${ARM_SUBSCRIPTION_ID}" --query "[].{Name:name} | [? contains(Name,'S-Password')] | [0]"  -o tsv)
-                if [ -z $SPasswordfromVault ]; then
+                if [ ${SPassword} == $SPasswordfromVault ]; then
+                  echo "##vso[task.setvariable variable=SPASSWORD;isOutput=true]${SPasswordfromVault}"
+                  echo -e "$green--- Password present in keyvault. In case of download errors check that user and password are correct ---$reset"
+                else
                   echo -e "$green--- Setting the S user name password in key vault ---$reset"
                   az keyvault secret set --name "S-Password" --vault-name $kv_name --value "${SPassword}" --subscription "${ARM_SUBSCRIPTION_ID}" --output none
                   echo "##vso[task.setvariable variable=SPASSWORD;isOutput=true]${SPassword}"
-                else
-                  echo "##vso[task.setvariable variable=SPASSWORD;isOutput=true]${SPasswordfromVault}"
-                  echo -e "$green--- Password present in keyvault. In case of download errors check that user and password are correct ---$reset"
                 fi
             displayName:                Prepare download
             name:                       Preparation
@@ -227,7 +210,7 @@ stages:
                   exit 2
                 fi
 
-                az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
+                az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
                 return_code=$?
                 if [ 0 != $return_code ]; then
                   echo -e "$boldred--- Login failed ---$reset"
@@ -235,22 +218,25 @@ stages:
                   exit $return_code
                 fi
 
-                command="ansible-playbook '-e "BOM_directory=${sample_path}" -e "bom_base_name=$(BOM_NAME)" -e "deployer_kv_name=$(KV_NAME)" -e "check_storage_account=$(check_storage_account)" ' ${{ parameters.sap_automation_repo_path }}/deploy/ansible/playbook_bom_downloader.yaml"
+                command="ansible-playbook '-e "download_directory=$(Agent.TempDirectory)" -e "BOM_directory=${sample_path}" -e "bom_base_name=$(BOM_NAME)" -e "deployer_kv_name=$(KV_NAME)" -e "check_storage_account=$(check_storage_account)" ' $ExtraParams ${{ parameters.sap_automation_repo_path }}/deploy/ansible/playbook_bom_downloader.yaml"
 
                 echo "##[section]Executing [$command]..."
                 echo "##[group]- output"
                 eval $command
+                return_code=$?
                 echo "##[endgroup]"
+                exit $return_code
             displayName:               Download
             name:                      download
             env:
-              ARM_CLIENT_ID:            $(CP_ARM_CLIENT_ID)
-              ARM_CLIENT_SECRET:        $(CP_ARM_CLIENT_SECRET)
-              ARM_TENANT_ID:            $(CP_ARM_TENANT_ID)
-              ARM_SUBSCRIPTION_ID:      $(CP_ARM_SUBSCRIPTION_ID)
-              SAP_AUTOMATION_REPO_PATH: ${{ parameters.sap_automation_repo_path }}
-              SAMPLE_REPO_PATH:         ${{ parameters.sample_repo_path }}
-              CONFIG_REPO_PATH:         ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
-              ExtraParams:              $(ExtraParams)
-            failOnStderr:               false
+              ARM_CLIENT_ID:                 $(CP_ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:             $(CP_ARM_CLIENT_SECRET)
+              ARM_TENANT_ID:                 $(CP_ARM_TENANT_ID)
+              ARM_SUBSCRIPTION_ID:           $(CP_ARM_SUBSCRIPTION_ID)
+              SAP_AUTOMATION_REPO_PATH:      ${{ parameters.sap_automation_repo_path }}
+              SAMPLE_REPO_PATH:              ${{ parameters.sample_repo_path }}
+              CONFIG_REPO_PATH:              ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
+              ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
+              ExtraParams:                   ${{ parameters.ExtraParams }}
+            failOnStderr:                    false
 
