pipeline updates

diff --git a/deploy/pipelines/05-DB-and-SAP-installation.yaml b/deploy/pipelines/05-DB-and-SAP-installation.yaml
--- a/deploy/pipelines/05-DB-and-SAP-installation.yaml
+++ b/deploy/pipelines/05-DB-and-SAP-installation.yaml
@@ -18,8 +18,9 @@ parameters:
   - name: bom_base_name
     displayName: BOM Base Name
     type: string
-    default: S41909SPS03_v0008ms
+    default: S41909SPS03_v0009ms
     values:
+      - S41909SPS03_v0009ms
       - S41909SPS03_v0008ms
       - S41909SPS03_v0007ms
       - BW4HANA2021SPS01_v0002ms
@@ -78,6 +79,11 @@ parameters:
 
   - name: highavailability
     displayName: SAP & DB High Availability Setup
+    type: boolean
+    default: false
+
+  - name: postinstallation
+    displayName: Post Installation Steps
     type: boolean
     default: false
 
@@ -440,4 +446,49 @@ stages:
               failOnStderr: false
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
+
+  - stage: Post_Installation_Steps
+    displayName: Post Installation Steps
+    jobs:
+      - job: Post_Installation_Steps
+        displayName: Post Installation Steps
+        steps:
+          - checkout: self
+            persistCredentials: true
+          - script: |
+              #!/bin/bash
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
+                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
+                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
+                cd $HOME; mkdir -p .sap_deployment_automation
+                echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
+                SID=$(echo $(sapsystemfolder) | cut -d'-' -f4 | xargs) 
+                if [ ! -n ${SID} ]; then
+                  echo "##vso[task.logissue type=error]SID was not defined in the parameter file."
+                  exit 2
+                fi
+              echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
+                git pull --append origin $(Branch)
+                git config --global user.email "$(Build.RequestedForEmail)"
+                git config --global user.name "$(Build.RequestedFor)"
+                cd $(Build.Repository.LocalPath)
+                added=0
+                if [ -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/${SID}_*.zip ]; then
+                  git add $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/${SID}_*.zip
+                  added=1
+                fi
+                if [ 1 == $added ]; then
+                  git commit -m "Added updates from devops Ansible deployment $(Build.DefinitionName) [skip ci]"
+
+                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:$(Branch)
+                fi
+                if [ -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/${SID}.md ]; then
+                  echo "##vso[task.uploadsummary]$HOME/SYSTEM/$(sapsystemfolder)/${SID}.md"
+                fi
+            displayName: Copy Log files
+            env:
+              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+            failOnStderr: false
+
 ...
