Update 06-post-installation-tooling.yaml

diff --git a/deploy/pipelines/06-post-installation-tooling.yaml b/deploy/pipelines/06-post-installation-tooling.yaml
--- a/deploy/pipelines/06-post-installation-tooling.yaml
+++ b/deploy/pipelines/06-post-installation-tooling.yaml
@@ -42,11 +42,18 @@ trigger:                               none
 
 variables:
   - group:                             "SDAF-General"
+
   - group:                             SDAF-${{ parameters.environment }}
+
   - name:                              sap_system_folder
     value:                             ${{ parameters.sap_system_configuration_name }}
+
+  - name:                              sap_system_configuration
+    value:                             $(sap_system_folder).tfvars
+
   - name:                              bom
     value:                             ${{ parameters.bom_base_name }}
+
   - name:                              agent_name
     value:                             $[coalesce(variables['POOL'], variables['Agent'])]
 
@@ -73,49 +80,71 @@ stages:
             persistCredentials:        true
           - bash: |
               #!/bin/bash
+              echo "##vso[build.updatebuildnumber]Running Post Installation on Systems defined in $(sap_system_folder)"
               green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
-              if [[ ! -f /etc/profile.d/deploy_server.sh ]]; then
-                echo -e "$green --- Install dos2unix ---$reset"
-                  sudo apt-get -qq install dos2unix
-              fi
-              echo -e "$green--- --- Convert config file to UX format ---$reset"
-              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
-                cd $HOME
+
+                     HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
+              ENVIRONMENT=$(echo $(sap_system_folder) | awk -F'-' '{print $1}' | xargs) ; echo "Environment: $ENVIRONMENT"
+                 LOCATION=$(echo $(sap_system_folder) | awk -F'-' '{print $2}' | xargs) ; echo "Location:    $LOCATION"
+                  NETWORK=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo "Network:     $NETWORK"
+                      SID=$(echo $(sap_system_folder) | awk -F'-' '{print $4}' | xargs) ; echo "SID:         $SID"
 
               echo -e "$green--- Configure devops CLI extension ---$reset"
-                devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
-                if [ -z "$devops_extension_installed" ]; then
-                  az extension add --name azure-devops --output none
-                fi
-                az devops configure -d organization=$(System.CollectionUri)
-                az devops configure -d project=$(System.TeamProject)
-                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
+                    devops_extension_installed=$(az extension list --query [].path | grep azure-devops)
+                    if [ -z "$devops_extension_installed" ]; then
+                      az extension add --name azure-devops --output none
+                    fi
 
-                export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
-                echo '$(variable_group) id: ' $VARIABLE_GROUP_ID
-                if [ -z ${VARIABLE_GROUP_ID} ]; then
-                    echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
-                    exit 2
-                fi
+                    az devops configure -d organization=$(System.CollectionUri)
+                    az devops configure -d project=$(System.TeamProject)
+                    export VARIABLE_GROUP_ID=$(az pipelines variable-group list --query "[?name=='$(variable_group)'].id | [0]")
+                    echo VARIABLE_GROUP_ID ${VARIABLE_GROUP_ID}
+                    if [ -z ${VARIABLE_GROUP_ID} ]; then
+                        echo "##vso[task.logissue type=error]Variable group $(variable_group) could not be found."
+                        exit 2
+                    fi
 
-              echo -e "$green--- Validations ---$reset"
-                ENVIRONMENT=$(echo $(sap_system_folder) | awk -F'-' '{print $1}' | xargs) ; echo Environment $ENVIRONMENT
-                   LOCATION=$(echo $(sap_system_folder) | awk -F'-' '{print $2}' | xargs) ; echo Location    $LOCATION
-                    NETWORK=$(echo $(sap_system_folder) | awk -F'-' '{print $3}' | xargs) ; echo Virtual network logical name $NETWORK
-                        SID=$(echo $(sap_system_folder) | awk -F'-' '{print $4}' | xargs) ; echo SID $SID
-
-                environment_file_name=$HOME/.sap_deployment_automation/$ENVIRONMENT$LOCATION$NETWORK ; echo configuration_file $environment_file_name
-                          params_file=$HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml              ;  echo sap_parameters_file $params_file
-
-              if [[ "azure pipelines" == $(this_agent) ]]; then
-                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-${ENVIRONMENT} variable group using the 'POOL' variable."
+                if [ ! -f $HOME/SYSTEM/$(sap_system_folder)/$(sap_system_configuration) ]; then
+                  echo -e "$boldred--- $(sap_system_configuration) was not found ---$reset"
+                  echo "##vso[task.logissue type=error]File $(sap_system_configuration) was not found."
                   exit 2
                 fi
 
+                environment_file_name=$HOME/.sap_deployment_automation/${ENVIRONMENT}${LOCATION}${NETWORK}
+
                 if [ ! -f $environment_file_name ]; then
-                  echo -e "$boldred--- $environment_file_name was not found ---$reset"
-                  echo "##vso[task.logissue type=error]Workload zone configuration file $environment_file_name was not found."
+                  echo -e "$boldred--- $ENVIRONMENT$LOCATION$NETWORK was not found ---$reset"
+                  echo "##vso[task.logissue type=error]Please rerun the workload zone deployment. Workload zone configuration file $ENVIRONMENT$LOCATION$NETWORK was not found."
+                  exit 2
+                fi
+
+                if [ -z $(ARM_SUBSCRIPTION_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
+                  exit 2
+                fi
+
+                if [ -z $(ARM_CLIENT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
+                  exit 2
+                fi
+
+                if [ -z $ARM_CLIENT_SECRET ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
+                  exit 2
+                fi
+
+                if [ -z $(ARM_TENANT_ID) ]; then
+                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
+                  exit 2
+                fi
+
+                if [ -z ${SID} ]; then
+                  echo "##vso[task.logissue type=error]SID was not defined in the parameter file."
+                  exit 2
+                fi
+
+                if [[ "azure pipelines" == $(this_agent) ]]; then
+                  echo "##vso[task.logissue type=error]Please use a self hosted agent for this playbook. Define it in the SDAF-${ENVIRONMENT} variable group using the 'POOL' variable."
                   exit 2
                 fi
 
@@ -127,11 +156,6 @@ stages:
                   dos2unix -q $HOME/SYSTEM/$(sap_system_folder)/sap-parameters.yaml
                 fi
                 
-                if [ ! -n ${SID} ]; then
-                  echo "##vso[task.logissue type=error]SID was not found in $(sap_system_folder)."
-                  exit 2
-                fi
-
                 if [ ! -f $HOME/SYSTEM/$(sap_system_folder)/${SID}_hosts.yaml ]; then
                   echo -e "$boldred--- $HOME/SYSTEM/$(sap_system_folder)/${SID}_hosts.yaml was not found ---$reset"
                   echo "##vso[task.logissue type=error]File $HOME/SYSTEM/$(sap_system_folder)/${SID}_hosts.yaml was not found."
@@ -139,7 +163,7 @@ stages:
                 fi
                 dos2unix -q $HOME/SYSTEM/$(sap_system_folder)/${SID}_hosts.yaml
 
-                echo "##vso[build.updatebuildnumber]Deploying $(sap_system_folder) using BoM ${bom_file}"
+                echo "##vso[build.updatebuildnumber]Running Post Installation on $(sap_system_folder) using BoM ${bom_file}"
 
                 echo "##vso[task.setvariable variable=SID;isOutput=true]${SID}"
                 echo "##vso[task.setvariable variable=SAP_PARAMETERS;isOutput=true]sap-parameters.yaml"
@@ -179,18 +203,16 @@ stages:
                 cp sap-parameters.yaml artifacts/.
                 cp ${SID}_hosts.yaml artifacts/.
 
-              echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
-                added=0
-                git config --global user.email "$(Build.RequestedForEmail)"
-                git config --global user.name "$(Build.RequestedFor)"
-                git checkout -q $(Branch)  &> /dev/null
-                2> >(while read line; do (>&2 echo "STDERROR: $line"); done)
             name:                      Preparation
             displayName:               Preparation for Ansible
             env:
-              SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
-              ARM_SUBSCRIPTION_ID:     $(ARM_SUBSCRIPTION_ID)
-              ANSIBLE_HOST_KEY_CHECKING: false
+              SYSTEM_ACCESSTOKEN:             $(System.AccessToken)
+              ARM_SUBSCRIPTION_ID:            $(ARM_SUBSCRIPTION_ID)
+              ARM_CLIENT_ID:                  $(ARM_CLIENT_ID)
+              ARM_CLIENT_SECRET:              $(ARM_CLIENT_SECRET)
+              ARM_TENANT_ID:                  $(ARM_TENANT_ID)
+              AZURE_DEVOPS_EXT_PAT:           $(PAT)
+              DEPLOYMENT_REPO_PATH:           $(Build.Repository.LocalPath)
             failOnStderr:              true
           - publish:                   $(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)/artifacts
             artifact:                  ansible_data
@@ -338,6 +360,31 @@ stages:
               inventoryFileOnAgentMachine: $(Pipeline.Workspace)/ansible_data/$(SID_hosts)
               args:                    '--private-key $(Pipeline.Workspace)/ansible_data/$(CONFIGURATION_NAME)_sshkey -e "@$(Pipeline.Workspace)/ansible_data/$(SAP_parameters)" -e "_workspace_directory=$(parameters_folder)" $(ExtraParams)'
               failOnStderr:            false
+          - script: |
+              #!/bin/bash
+                green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+                echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
+                cd $(Build.Repository.LocalPath)
+              echo -e "$green--- Checkout $(Build.SourceBranchName) ---$reset"
+                git checkout -q -b $(Build.SourceBranchName)
+              echo -e "$green--- git status ---$reset"
+                git status
+                added=0
+              echo -e "$green--- Running git add in case of new hcmtresult files ---$reset"
+              if [ $(ls $(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)/logs/hcmtresult*.zip | wc -l ) -gt 0 ] ; then
+                git add --ignore-errors $(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)/logs/hcmtresult*.zip
+                added=1
+              fi
+              echo -e "$green--- Running git push in case files have been added ---$reset"
+              if [ 1 == $added ]; then
+                  git config --global user.email "$(Build.RequestedForEmail)"
+                  git config --global user.name "$(Build.RequestedFor)"
+                  git commit -m "Added updates from devops deployment $(Build.DefinitionName) [skip ci]"
+                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --set-upstream origin $(Build.SourceBranchName)
+              echo -e "$green--- git status ---$reset"
+              git status
+              fi
+            displayName:               Upload HCMT result to Azure Devops
             env:
               ANSIBLE_DISPLAY_SKIPPED_HOSTS: false
               ANSIBLE_HOST_KEY_CHECKING:     false
@@ -345,29 +392,15 @@ stages:
               DEPLOYMENT_REPO_PATH:          $(DEPLOYMENT_REPO_PATH)
               ANSIBLE_COLLECTIONS_PATHS:     ~/.ansible/collections:/opt/ansible/collections
             continueOnError:           false
-          - script: |
-              #!/bin/bash
-              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
-              echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
-                git config --global user.email "$(Build.RequestedForEmail)"
-                git config --global user.name "$(Build.RequestedFor)"
-                git checkout -q $(Branch)
-                git pull
-                cd $(Build.Repository.LocalPath)
-                added=0
-                if [ $(ls $(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)/logs/*.zip | wc -l ) -gt 0 ] ; then
-                  git add --ignore-errors $(Deployment_Configuration_Path)/SYSTEM/$(sap_system_folder)/logs
-                  added=1
-                fi
-                if [ 1 == $added ]; then
-                  git commit -m "Added Logs Database Installation $(Build.DefinitionName) [skip ci]" 
-                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push 
-                fi
-            displayName:               Copy HCMT Log files
 
-  - stage:                             Post_Installation_Steps
+  - stage: Post_Installation_Steps
     displayName:                       Post Installation Steps
     condition:                         always()
+    dependsOn:
+      - Preparation_for_Ansible
+      - Validate_Parameters
+      - Software_Acquisition
+      - HCMT
     jobs:
       - job:                           Post_Installation_Steps
         displayName:                   Post Installation Steps
@@ -375,48 +408,12 @@ stages:
           SID_hosts:                   $[ stageDependencies.Preparation_for_Ansible.Preparation_step.outputs['Preparation.HOSTS'] ]
           SAP_parameters:              $[ stageDependencies.Preparation_for_Ansible.Preparation_step.outputs['Preparation.SAP_PARAMETERS'] ]
           parameters_folder:           $[ stageDependencies.Preparation_for_Ansible.Preparation_step.outputs['Preparation.FOLDER'] ]
-          key_path:                    $[ stageDependencies.Preparation_for_Ansible.Preparation_step.outputs['Preparation.SSHKEY'] ]
           DEPLOYMENT_REPO_PATH:        $[ stageDependencies.Preparation_for_Ansible.Preparation_step.outputs['Preparation.DEPLOYMENT_REPO_PATH'] ]
         steps:
           - task:                      PostBuildCleanup@3
-          - checkout:                  none
-            persistCredentials:        true
           - script: |
               #!/bin/bash
-              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
-              echo -e "$green--- Update .sap_deployment_automation/config as DEPLOYMENT_REPO_PATH can change on devops agent ---$reset"
-                export DEPLOYMENT_REPO_PATH=$(Build.Repository.LocalPath)
-                export HOME=$(Build.Repository.LocalPath)/$(Deployment_Configuration_Path)
-                cd $HOME; mkdir -p .sap_deployment_automation
-                echo DEPLOYMENT_REPO_PATH=$DEPLOYMENT_REPO_PATH > .sap_deployment_automation/config
-                SID=$(echo $(sapsystemfolder) | cut -d'-' -f4 | xargs)
-                if [ ! -n ${SID} ]; then
-                  echo "##vso[task.logissue type=error]SID was not defined in the parameter file."
-                  exit 2
-                fi
-              echo -e "$green--- Add & update files in the DevOps Repository ---$reset"
-                git checkout -q $(Branch)
-                git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" pull
-                git config --global user.email "$(Build.RequestedForEmail)"
-                git config --global user.name "$(Build.RequestedFor)"
-                cd $(Build.Repository.LocalPath)
-                added=0
-                if [ -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/logs/${SID}_*.zip ]; then
-                  git add $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/logs/${SID}_*.zip
-                  added=1
-                fi
-                if [ -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/logs/hcmtresult-*.zip ]; then
-                  git add $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/logs/hcmtresult-*.zip
-                  added=1
-                fi
-                if [ 1 == $added ]; then
-                  git commit -m "Added updates from devops Ansible deployment $(Build.DefinitionName) [skip ci]"
-                  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push
-                fi
-                if [ -f $(Deployment_Configuration_Path)/SYSTEM/$(sapsystemfolder)/${SID}.md ]; then
-                  echo "##vso[task.uploadsummary]$HOME/SYSTEM/$(sapsystemfolder)/${SID}.md"
-                fi
-
+              echo "nothing to do here right now"
             displayName:               Copy Log files
             env:
               SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
