Refactor pipeline script to include missing variable checks

diff --git a/deploy/pipelines/10-remover-terraform.yaml b/deploy/pipelines/10-remover-terraform.yaml
--- a/deploy/pipelines/10-remover-terraform.yaml
+++ b/deploy/pipelines/10-remover-terraform.yaml
@@ -101,25 +101,69 @@ stages:
                   exit 2
                 fi
 
-                if [ -z $WL_ARM_SUBSCRIPTION_ID ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined."
-                  exit 2
+                if [ $USE_MSI != "true" ]; then
+
+                    if [ -z $WL_ARM_SUBSCRIPTION_ID ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ $WL_ARM_SUBSCRIPTION_ID == '$$(ARM_SUBSCRIPTION_ID)' ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_SUBSCRIPTION_ID was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $WL_ARM_CLIENT_ID ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ $WL_ARM_CLIENT_ID == '$$(ARM_CLIENT_ID)' ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $WL_ARM_CLIENT_SECRET ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ $WL_ARM_CLIENT_SECRET == '$$(ARM_CLIENT_SECRET)' ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $WL_ARM_TENANT_ID ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ $WL_ARM_TENANT_ID == '$$(ARM_TENANT_ID)' ]; then
+                        echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined in the $(variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $CP_ARM_SUBSCRIPTION_ID ]; then
+                        echo "##vso[task.logissue type=error]Variable CP_ARM_SUBSCRIPTION_ID was not defined in the $(parent_variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $CP_ARM_CLIENT_ID ]; then
+                        echo "##vso[task.logissue type=error]Variable CP_ARM_CLIENT_ID was not defined in the $(parent_variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $CP_ARM_CLIENT_SECRET ]; then
+                        echo "##vso[task.logissue type=error]Variable CP_ARM_CLIENT_SECRET was not defined in the $(parent_variable_group) variable group."
+                        exit 2
+                    fi
+
+                    if [ -z $CP_ARM_TENANT_ID ]; then
+                        echo "##vso[task.logissue type=error]Variable CP_ARM_TENANT_ID was not defined in the $(parent_variable_group) variable group."
+                        exit 2
+                    fi
                 fi
 
-                if [ -z $WL_ARM_CLIENT_ID ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_ID was not defined."
-                  exit 2
-                fi
-
-                if [ -z $WL_ARM_CLIENT_SECRET ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_CLIENT_SECRET was not defined."
-                  exit 2
-                fi
-
-                if [ -z $WL_ARM_TENANT_ID ]; then
-                  echo "##vso[task.logissue type=error]Variable ARM_TENANT_ID was not defined."
-                  exit 2
-                fi
 
               # Check if running on deployer
               if [[ ! -f /etc/profile.d/deploy_server.sh ]]; then
@@ -137,14 +181,14 @@ stages:
                   unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
                   rm -f terraform_$(tf_version)_linux_amd64.zip
               else
-                if [ $LOGON_USING_SPN == "true" ]; then
-                  echo "Logon Using SPN"
+                if [ $USE_MSI != "true" ]; then
+                  echo "Using SPN"
 
                   export ARM_CLIENT_ID=$WL_ARM_CLIENT_ID
                   export ARM_CLIENT_SECRET=$WL_ARM_CLIENT_SECRET
                   export ARM_TENANT_ID=$WL_ARM_TENANT_ID
                   export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
-                  export ARM_USE_MSI=false
+                  unset ARM_USE_MSI
                   az login --service-principal --username $WL_ARM_CLIENT_ID --password=$WL_ARM_CLIENT_SECRET --tenant $WL_ARM_TENANT_ID --output none
                   return_code=$?
                   if [ 0 != $return_code ]; then
@@ -154,6 +198,8 @@ stages:
                   fi
                 else
                   export ARM_USE_MSI=true
+                  export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
+                  unset ARM_TENANT_ID
                   az login --identity --allow-no-subscriptions --output none
                 fi
               fi
@@ -302,14 +348,14 @@ stages:
               else
                 echo -e "$green --- Running on deployer ---$reset"
 
-                if [ $LOGON_USING_SPN == "true" ]; then
+                if [ $USE_MSI != "true" ]; then
                   echo "Using SPN"
 
                   export ARM_CLIENT_ID=$WL_ARM_CLIENT_ID
                   export ARM_CLIENT_SECRET=$WL_ARM_CLIENT_SECRET
                   export ARM_TENANT_ID=$WL_ARM_TENANT_ID
                   export ARM_SUBSCRIPTION_ID=$WL_ARM_SUBSCRIPTION_ID
-                  export ARM_USE_MSI=false
+                  unset ARM_USE_MSI
                   az login --service-principal --username $WL_ARM_CLIENT_ID --password=$WL_ARM_CLIENT_SECRET --tenant $WL_ARM_TENANT_ID --output none
                   return_code=$?
                   if [ 0 != $return_code ]; then
