logon as SPN for removal

diff --git a/deploy/pipelines/12-remove-control-plane.yaml b/deploy/pipelines/12-remove-control-plane.yaml
--- a/deploy/pipelines/12-remove-control-plane.yaml
+++ b/deploy/pipelines/12-remove-control-plane.yaml
@@ -125,9 +125,16 @@ stages:
                     fi
                     unzip -qq terraform_$(tf_version)_linux_amd64.zip ; sudo mv terraform /bin/
                     rm -f terraform_$(tf_version)_linux_amd64.zip
-                else
-                  source /etc/profile.d/deploy_server.sh
                 fi
+
+                az login --service-principal --username $ARM_CLIENT_ID --password=$ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none
+                return_code=$?
+                if [ 0 != $return_code ]; then
+                  echo -e "$boldred--- Login failed ---$reset"
+                  echo "##vso[task.logissue type=error]az login failed."
+                  exit $return_code
+                fi
+
 
               echo -e "$green--- Convert config files to UX format ---$reset"
                 dos2unix -q $CONFIG_REPO_PATH/DEPLOYER/$(deployer_folder)/$(deployer_configuration_file)
