Update ADO pipeline fixes to report merge conflicts

diff --git a/deploy/pipelines/20-update-ado-repository.yaml b/deploy/pipelines/20-update-ado-repository.yaml
--- a/deploy/pipelines/20-update-ado-repository.yaml
+++ b/deploy/pipelines/20-update-ado-repository.yaml
@@ -47,8 +47,9 @@ stages:
         steps:
           - checkout:                  self
             persistCredentials:        true
-          - script: |
+          - bash: |
               #!/bin/bash
+              green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
 
               git config --global user.email "$(Build.RequestedForEmail)"
               git config --global user.name "$(Build.RequestedFor)"
@@ -57,21 +58,36 @@ stages:
 
               git checkout -q $(branch) 
               git pull -q
-              
+
               git remote add remote-repo $(repository) >> /tmp/$(log) 2>&1
               
-              git pull -q --commit remote-repo $(branch) 
+              git pull -q --commit remote-repo $(branch)  >> /tmp/$(log) 2>&1
+              pull_return_code=$?
+
+              grep CONFLICT /tmp/$(log) | while read -r conflict ; do
+                echo $conflict
+                echo "##vso[task.logissue type=error]$conflict"
+              done
 
               if [[ "$(force)" == "True" ]]; then
                 echo "running git push to ADO with force option" 
-                git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --force origin HEAD:$(branch)  >> /tmp/$(log) 2>&1
+                if ! git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push --force origin HEAD:$(branch)  >> /tmp/$(log) 2>&1
+                then 
+                   echo -e "$red--- Failed to push ---$reset"
+                   exit 1
+                fi
               else
                 echo "running git push to ADO" 
-                git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push  >> /tmp/$(log) 2>&1
+                if ! git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push  >> /tmp/$(log) 2>&1
+                then 
+                   echo -e "$red--- Failed to push ---$reset"
+                   exit 1
+                fi
+
               fi
               return_code=$?
-              cat /tmp/$(log)
-              exit $return_code
+              
+              exit $return_code+$pull_return_code
               
             displayName:               Update ADO repository
             env:
