sap installation pipeline id support

diff --git a/deploy/pipelines/21-deploy-web-app.yaml b/deploy/pipelines/21-deploy-web-app.yaml
--- a/deploy/pipelines/21-deploy-web-app.yaml
+++ b/deploy/pipelines/21-deploy-web-app.yaml
@@ -30,9 +30,13 @@ parameters:
 
   - name:                              system_deployment_pipeline
     displayName:                       "SAP system deployment pipeline name"
-
     type:                              string
     default:                           SAP system deployment (infrastructure)
+
+  - name:                              sap_install_pipeline
+    displayName:                       "SAP configuration and installation pipeline name"
+    type:                              string
+    default:                           Configuration and SAP installation
 
 variables:
   - group:                             "SDAF-General"
@@ -59,6 +63,9 @@ variables:
   - name:                              system_deployment_pipeline_name
     value:                             ${{ parameters.system_deployment_pipeline }}
 
+  - name:                              sap_install_pipeline_name
+    value:                             ${{ parameters.sap_install_pipeline }}
+
   - name:                              secret
     value:                             $[format('@Microsoft.KeyVault(SecretUri=https://{0}.vault.azure.net/secrets/PAT/)', variables.keyvault)]
 
@@ -82,6 +89,7 @@ stages:
 
               WORKLOADZONE_PIPELINE_ID=$(az pipelines list --query "[?name=='$(workload_zone_deployment_pipeline_name)'].id | [0]")
               SYSTEM_PIPELINE_ID=$(az pipelines list --query "[?name=='$(system_deployment_pipeline_name)'].id | [0]")
+              SAP_INSTALL_PIPELINE_ID=$(az pipelines list --query "[?name=='$(sap_install_pipeline_name)'].id | [0]")
               SDAF_GENERAL_GROUP_ID=$(az pipelines variable-group list --group-name "SDAF-General" --query '[0].id')
 
               if [ -z $(PAT) ]; then
@@ -99,8 +107,14 @@ stages:
                 exit 2
               fi
 
+              if [ -z $SAP_INSTALL_PIPELINE_ID ]; then
+                echo "##vso[task.logissue type=error]Pipeline '$(sap_install_pipeline_name)' does not exist. Please create it or correct the name to continue"
+                exit 2
+              fi
+
               echo "##vso[task.setvariable variable=WORKLOADZONE_PIPELINE_ID]${WORKLOADZONE_PIPELINE_ID}"
               echo "##vso[task.setvariable variable=SYSTEM_PIPELINE_ID]${SYSTEM_PIPELINE_ID}"
+              echo "##vso[task.setvariable variable=SAP_INSTALL_PIPELINE_ID]${SAP_INSTALL_PIPELINE_ID}"
               echo "##vso[task.setvariable variable=SDAF_GENERAL_GROUP_ID]${SDAF_GENERAL_GROUP_ID}"
 
               echo "##vso[build.updatebuildnumber]Deploying the Web Application $(webappName)"
@@ -137,6 +151,7 @@ stages:
                                                   -SourceBranch "$(Build.SourceBranchName)"
                                                   -WORKLOADZONE_PIPELINE_ID $(WORKLOADZONE_PIPELINE_ID)
                                                   -SYSTEM_PIPELINE_ID $(SYSTEM_PIPELINE_ID)
+                                                  -SAP_INSTALL_PIPELINE_ID $(SAP_INSTALL_PIPELINE_ID)
                                                   -SDAF_GENERAL_GROUP_ID $(SDAF_GENERAL_GROUP_ID)
                                                   -IS_PIPELINE_DEPLOYMENT true
                                                   -PAT $(secret)'
