Update Azure NVMe swap configuration script to handle initramfs updates for non-RHEL systems

diff --git a/deploy/ansible/roles-os/1.1-swap/files/88-azure-nvme-swap-conf b/deploy/ansible/roles-os/1.1-swap/files/88-azure-nvme-swap-conf
--- a/deploy/ansible/roles-os/1.1-swap/files/88-azure-nvme-swap-conf
+++ b/deploy/ansible/roles-os/1.1-swap/files/88-azure-nvme-swap-conf
@@ -156,7 +156,24 @@ echo "LABEL=$RAID0_FILESYSTEM_LABEL $mount_point $filesystem defaults,nofail 0 0
 
 # Add RAID 0 array to mdadm.conf
 mdadm --detail --scan >> $mdadm_conf_path
-update-initramfs -u
+# Update initramfs to include the new mdadm configuration for OS other than RHEL/OracleLinux
+if ! grep -E "ID=RHEL|ID=\"OracleLinux\"" /etc/os-release > /dev/null; then
+    printf "\nUpdating initramfs with new mdadm configuration..\n"
+    update-initramfs -u
+    if [ $? -ne 0 ]; then
+        printf "Failed to update initramfs\n"
+        exit 1
+    fi
+    printf "The operation has completed successfully.\n"
+elif grep -E "ID=RHEL|ID=\"OracleLinux\"" /etc/os-release > /dev/null;  then
+    printf "\nUpdating dracut with new mdadm configuration..\n"
+    dracut -f
+    if [ $? -ne 0 ]; then
+        printf "Failed to update initramfs\n"
+        exit 1
+    fi
+    printf "The operation has completed successfully.\n"
+fi
 
 # Mount the partition
 printf "\nMounting filesystem to $mount_point..\n"
